/**
à*à=====================================================
à*àCOMPARISONàMODULEà-àMedizintechnikàVergleich
à*àSeitenweiseàVergleichàmitàVisualisierungen
à*à=====================================================
à*/

classàComparisonModuleà{
ààconstructor()à{
ààààthis.device1à=ànull;
ààààthis.device2à=ànull;
ààààthis.comparisonActiveà=àfalse;
ààààthis.modalElementà=ànull;

ààààthis.initializeUI();
ààààthis.attachEventListeners();
àà}

àà/**
ààà*àErstelleàdasàVergleichs-ModalàElement
ààà*/
ààinitializeUI()à{
ààààconstàmodalà=àdocument.createElement('div');
ààààmodal.idà=à'comparison-modal';
ààààmodal.classList.add('comparison-modal');
ààààmodal.innerHTMLà=à`
àààààà<divàclass="comparison-overlay"></div>
àààààà<divàclass="comparison-container">
àààààààà<divàclass="comparison-header">
àààààààààà<h2>MedizintechnikàVergleich</h2>
àààààààààà<buttonàclass="comparison-close">&times;</button>
àààààààà</div>
àààààààà<divàclass="comparison-body"></div>
àààààà</div>
àààà`;
ààààdocument.body.appendChild(modal);
ààààthis.modalElementà=àmodal;

àààà//àCloseàHandler
ààààmodal.querySelector('.comparison-close').addEventListener('click',à()à=>à{
ààààààthis.closeComparison();
àààà});
ààààmodal.querySelector('.comparison-overlay').addEventListener('click',à()à=>à{
ààààààthis.closeComparison();
àààà});
àà}

àà/**
ààà*àEventàListeneràfüràGeräte-Auswahl
ààà*/
ààattachEventListeners()à{
àààà//àDeviceàCardàClick
ààààdocument.addEventListener('click',à(e)à=>à{
ààààààifà(e.target.classList.contains('device-card-select'))à{
ààààààààthis.selectDevice(e.target.dataset.deviceId);
àààààà}
àààà});

àààà//àVergleichs-Button
ààààdocument.getElementById('compareBtn')?.addEventListener('click',à()à=>à{
ààààààifà(this.device1à&&àthis.device2)à{
ààààààààthis.displayComparison();
àààààà}
àààà});

àààà//àVergleichsmodusàToggle
ààààdocument.getElementById('compareToggle')?.addEventListener('change',à(e)à=>à{
ààààààthis.toggleComparisonMode(e.target.checked);
àààà});
àà}

àà/**
ààà*àGerätàfüràVergleichàauswählen
ààà*/
ààselectDevice(deviceId)à{
ààààconstàdeviceà=àMedicalDevicesDatabase.getDeviceById(deviceId);
ààààifà(!device)àreturn;

ààààifà(!this.device1)à{
ààààààthis.device1à=àdevice;
ààààààthis.updateCompareState();
àààà}àelseàifà(!this.device2à&&àdevice.idà!==àthis.device1.id)à{
ààààààthis.device2à=àdevice;
ààààààthis.updateCompareState();
àààà}
àà}

àà/**
ààà*àGerätàausàVergleichàentfernen
ààà*/
ààremoveDevice(deviceId)à{
ààààifà(this.device1à&&àthis.device1.idà===àdeviceId)à{
ààààààthis.device1à=ànull;
àààà}àelseàifà(this.device2à&&àthis.device2.idà===àdeviceId)à{
ààààààthis.device2à=ànull;
àààà}

àààà//àShiftàdevice2àtoàdevice1àifàdevice1àwasàremoved
ààààifà(!this.device1à&&àthis.device2)à{
ààààààthis.device1à=àthis.device2;
ààààààthis.device2à=ànull;
àààà}
ààààthis.updateCompareState();
àà}

àà/**
ààà*àUpdateàUIànachàAuswahl
ààà*/
ààupdateCompareState()à{
ààààconstàcountà=à(this.device1à?à1à:à0)à+à(this.device2à?à1à:à0);
ààààconstàbtnà=àdocument.getElementById('compareBtn');
ààààifà(btn)à{
ààààààbtn.textContentà=à`Vergleichenà(${count}/2)`;
ààààààbtn.disabledà=àcountà<à2;
àààà}
àà}

àà/**
ààà*àVergleichsmodusàToggle
ààà*/
ààtoggleComparisonMode(enabled)à{
ààààconstàcheckboxesà=àdocument.querySelectorAll'[data-compare-checkbox]');
ààààcheckboxes.forEach(cbà=>à{
ààààààcb.style.displayà=àenabledà?à'block'à:à'none';
àààà});

ààààifà(!enabled)à{
ààààààthis.device1à=ànull;
ààààààthis.device2à=ànull;
ààààààthis.updateCompareState();
ààààààcheckboxes.forEach(cbà=>àcb.checkedà=àfalse);
àààà}
àà}

àà/**
ààà*àZeigeàVergleichs-Modal
ààà*/
ààdisplayComparison()à{
ààààconstàbodyà=àthis.modalElement.querySelector('.comparison-body');

ààààbody.innerHTMLà=à`
àààààà<divàclass="comparison-grid">
àààààààà${this.renderDeviceColumn(this.device1)}
àààààààà${this.renderDeviceColumn(this.device2)}
àààààà</div>
àààààà<divàclass="comparison-metrics">
àààààààà${this.renderMetricsComparison()}
àààààà</div>
àààààà<divàclass="comparison-suitability">
àààààààà${this.renderSuitabilityComparison()}
àààààà</div>
àààààà<divàclass="comparison-details">
àààààààà${this.renderDetailsComparison()}
àààààà</div>
àààà`;

ààààthis.modalElement.classList.add('active');
ààààdocument.body.style.overflowà=à'hidden';

àààà//àTriggeràanimationsàforàbars
ààààsetTimeout(()à=>à{
ààààààconstàanimatedBarsà=àbody.querySelectorAll'.animated-bar');
ààààààanimatedBars.forEach(barà=>à{
ààààààààconstàtargetWidthà=àbar.getAttribute('data-target-width');
ààààààààbar.style.widthà=àtargetWidth;
àààààà});
àààà},à50);à//àslightàdelayàtoàallowàrenderingàbeforeàtransition
àà}

àà/**
ààà*àRenderàeinzelneàGerät-Spalte
ààà*/
ààrenderDeviceColumn(device)à{
ààààreturnà`
àààààà<divàclass="comparison-device-column">
àààààààà<divàclass="device-column-header">
àààààààààà<divàclass="device-icon">${device.icon}</div>
àààààààààà<h3>${device.name}</h3>
àààààààààà<pàclass="device-category">${device.category}</p>
àààààààà</div>
àààààààà
àààààààà<divàclass="device-description">
àààààààààà<p>${device.description}</p>
àààààààà</div>
àààààààà
àààààààà<divàclass="device-applications">
àààààààààà<h4>Anwendungen:</h4>
àààààààààà<ul>
àààààààààààà${device.applications.map(aà=>à`<li>${a}</li>`).join('')}
àààààààààà</ul>
àààààààà</div>
àààààààà
àààààààà<divàclass="device-highlights">
àààààààààà<divàclass="highlight-section">
àààààààààààà<h4>àVorteile:</h4>
àààààààààààà<ul>
àààààààààààààà${device.advantages.map(aà=>à`<li>${a}</li>`).join('')}
àààààààààààà</ul>
àààààààààà</div>
àààààààààà<divàclass="highlight-section">
àààààààààààà<h4> —¯¸àNachteile:</h4>
àààààààààààà<ul>
àààààààààààààà${device.disadvantages.map(dà=>à`<li>${d}</li>`).join('')}
àààààààààààà</ul>
àààààààààà</div>
àààààààà</div>
àààààà</div>
àààà`;
àà}

àà/**
ààà*àRenderàKennzahlen-Vergleich
ààà*/
ààrenderMetricsComparison()à{
ààààreturnà`
àààààà<divàclass="metrics-section">
àààààààà<h3>TechnischeàKennzahlen</h3>
àààààààà
àààààààà<divàclass="metric-row">
àààààààààà<divàclass="metric-label">Genauigkeit</div>
àààààààààà${this.renderMetricBars('accuracy')}
àààààààà</div>
àààààààà
àààààààà<divàclass="metric-row">
àààààààààà<divàclass="metric-label">Kostenà(Rel.)</div>
àààààààààà${this.renderMetricBars('cost')}
àààààààà</div>
àààààààà
àààààààà<divàclass="metric-row">
àààààààààà<divàclass="metric-label">Risiko</div>
àààààààààà${this.renderMetricBars('risk')}
àààààààà</div>
àààààààà
àààààààà<divàclass="metric-row">
àààààààààà<divàclass="metric-label">Bedienbarkeit</div>
àààààààààà${this.renderMetricBars('usability')}
àààààààà</div>
àààààààà
àààààààà<divàclass="metric-row">
àààààààààà<divàclass="metric-label">Effektivität</div>
àààààààààà${this.renderMetricBars('effectiveness')}
àààààààà</div>
àààààà</div>
àààà`;
àà}

àà/**
ààà*àRenderàMetric-BalkenàfüràbeideàGeräte
ààà*/
ààrenderMetricBars(metricKey)à{
ààààconstàvalue1à=àthis.device1.metrics[metricKey];
ààààconstàvalue2à=àthis.device2.metrics[metricKey];

àààà//àAddedàstyle="width:à0%"àinitiallyàandàthenàCSSàtransitionàwillàanimateàità
àààà//àtoàtheàactualàvalueàwhenàmodalàisàopened.àWe'llàuseàaàsmallàtimeoutàafteràrender.

ààààreturnà`
àààààà<divàclass="metric-bars">
àààààààà<divàclass="metric-bar">
àààààààààà<divàclass="bar-name"àtitle="${this.device1.name}">${this.device1.name.substring(0,à15)}...</div>
àààààààààà<divàclass="bar-container">
ààààààààààààà<divàclass="bar-fillàanimated-bar"àstyle="width:à0%;"àdata-target-width="${value1}%"></div>
àààààààààààà<spanàclass="bar-value">${value1}%</span>
àààààààààà</div>
àààààààà</div>
àààààààà
àààààààà<divàclass="metric-bar">
àààààààààà<divàclass="bar-name"àtitle="${this.device2.name}">${this.device2.name.substring(0,à15)}...</div>
àààààààààà<divàclass="bar-container">
àààààààààààà<divàclass="bar-fillàanimated-bar"àstyle="width:à0%;"àdata-target-width="${value2}%"></div>
àààààààààààà<spanàclass="bar-value">${value2}%</span>
àààààààààà</div>
àààààààà</div>
àààààà</div>
àààà`;
àà}

àà/**
ààà*àRenderàEignung-Vergleichà(Ampelsystem)
ààà*/
ààrenderSuitabilityComparison()à{
ààààconstàcategoriesà=à[
àààààà{àkey:à'forChildren',àlabel:à'FüràKinderàgeeignet'à},
àààààà{àkey:à'forElderly',àlabel:à'FüràSeniorenàgeeignet'à},
àààààà{àkey:à'forPregnant',àlabel:à'InàSchwangerschaftàsicher'à},
àààààà{àkey:à'forHospital',àlabel:à'ImàKrankenhaus'à},
àààààà{àkey:à'forHome',àlabel:à'Zuhauseàverwendbar'à}
àààà];

ààààreturnà`
àààààà<divàclass="suitability-section">
àààààààà<h3>°¦àEignungà&àIndikationen</h3>
àààààààà
àààààààà<divàclass="suitability-grid">
àààààààààà${categories.map(catà=>à`
àààààààààààà<divàclass="suitability-row">
àààààààààààààà<divàclass="suitability-label">${cat.label}</div>
àààààààààààààà<divàclass="suitability-indicators">
àààààààààààààààà${this.renderTrafficLight(this.device1.suitability[cat.key])}
àààààààààààààààà${this.renderTrafficLight(this.device2.suitability[cat.key])}
àààààààààààààà</div>
àààààààààààà</div>
àààààààààà`).join('')}
àààààààà</div>
àààààà</div>
àààà`;
àà}

àà/**
ààà*àRenderàAmpel-Symbolà(Rot/Gelb/Grün)àundàText
ààà*/
ààrenderTrafficLight(isApplicable)à{
ààààifà(isApplicableà===àundefinedà||àisApplicableà===ànull)à{
ààààààreturnà`
àààààààà<divàclass="indicator-wrapperàna">
àààààààààà<spanàclass="indicator-icon">ª</span>
àààààààààà<spanàclass="indicator-text">KeineàDaten</span>
àààààààà</div>
àààààà`;
àààà}

ààààifà(isApplicable)à{
ààààààreturnà`
àààààààà<divàclass="indicator-wrapperàyes">
àààààààààà<spanàclass="indicator-icon">°•</span>
àààààààààà<spanàclass="indicator-text">Geeignet</span>
àààààààà</div>
àààààà`;
àààà}àelseà{
ààààààreturnà`
àààààààà<divàclass="indicator-wrapperàno">
àààààààààà<spanàclass="indicator-icon">°´</span>
àààààààààà<spanàclass="indicator-text">Nichtàgeeignet</span>
àààààààà</div>
àààààà`;
àààà}
àà}

àà/**
ààà*àRenderàDetails-Vergleich
ààà*/
ààrenderDetailsComparison()à{
ààààreturnà`
àààààà<divàclass="details-section">
àààààààà<h3>°àTechnischeàDetails</h3>
àààààààà
àààààààà<divàclass="details-grid">
àààààààààà<divàclass="detail-column">
àààààààààààà<h4>${this.device1.name}</h4>
àààààààààààà${this.renderDetailsTable(this.device1.details)}
àààààààààààà<divàclass="meta-info">
àààààààààààààà<p><strong>Zuverlässigkeit:</strong>à${this.device1.reliability}%</p>
àààààààààààààà<p><strong>Wartung:</strong>à${this.device1.maintenance}</p>
àààààààààààà</div>
àààààààààà</div>
àààààààààà
àààààààààà<divàclass="detail-column">
àààààààààààà<h4>${this.device2.name}</h4>
àààààààààààà${this.renderDetailsTable(this.device2.details)}
àààààààààààà<divàclass="meta-info">
àààààààààààààà<p><strong>Zuverlässigkeit:</strong>à${this.device2.reliability}%</p>
àààààààààààààà<p><strong>Wartung:</strong>à${this.device2.maintenance}</p>
àààààààààààà</div>
àààààààààà</div>
àààààààà</div>
àààààà</div>
àààà`;
àà}

àà/**
ààà*àHilfsfunctionàfüràDetails-Tabelle
ààà*/
ààrenderDetailsTable(details)à{
ààààreturnà`
àààààà<tableàclass="details-table">
àààààààà${Object.entries(details).map(([key,àvalue])à=>à`
àààààààààà<tr>
àààààààààààà<tdàclass="detail-key">${this.humanizeKey(key)}</td>
àààààààààààà<tdàclass="detail-value">${value}</td>
àààààààààà</tr>
àààààààà`).join('')}
àààààà</table>
àààà`;
àà}

àà/**
ààà*àKonvertiereàSchlüsselàinàlesbaresàFormat
ààà*/
ààhumanizeKey(key)à{
ààààreturnàkey
àààààà.replace(/_/g,à'à')
àààààà.replace(/([A-Z])/g,à'à$1')
àààààà.replace(/^./,àstrà=>àstr.toUpperCase())
àààààà.trim();
àà}

àà/**
ààà*àSchlie—eàVergleichs-Modal
ààà*/
ààcloseComparison()à{
ààààthis.modalElement.classList.remove('active');
ààààdocument.body.style.overflowà=à'auto';
àà}

àà/**
ààà*àResetàVergleich
ààà*/
ààresetComparison()à{
ààààthis.device1à=ànull;
ààààthis.device2à=ànull;
ààààthis.updateCompareState();
àà}
}

//àInitializeàwennàDOMàready
document.addEventListener('DOMContentLoaded',à()à=>à{
ààwindow.comparisonModuleInstanceà=ànewàComparisonModule();
});
