/**
à*à===================================================================
à*à¡àMEDTECHGUIDEà-àPERFORMANCEàOPTIMIZATIONS
à*à===================================================================
à*àFeatures:
à*à-àLazyàLoadingàfüràBilder
à*à-àDeferredàSearchàIndexàLoading
à*à-àProgressiveàEnhancement
à*à-àResourceàPrioritization
à*/

//à===================================================================
//à°ü—¯¸àLAZYàLOADINGàFORàIMAGES
//à===================================================================

/**
à*àInitialisiertàLazyàLoadingàfüràBilderà(native,àmitàfallback)
à*/
functionàinitLazyLoading()à{
àà//àModerneàBrowserànutzenànativeàloading="lazy"
ààconstàlazyImagesà=àdocument.querySelectorAll'img[loading="lazy"]');
àà
ààifà(!lazyImages.length)à{
àààà//àFallback:àalleàimg-tagsàhinzufügen
ààààdocument.querySelectorAll'img').forEach(imgà=>à{
àààààà//àSkipàwennàaria-hidden
ààààààifà(img.closest('.skip-to-content,à.loader,à.spinner'))àreturn;
àààààà
ààààààimg.setAttribute('loading',à'lazy');
ààààààimg.setAttribute('decoding',à'async');
àààààà
àààààà//àFallbackàfüràalteàBrowser:àIntersectionObserver
ààààààifà('IntersectionObserver'àinàwindow)à{
ààààààààinitIntersectionObserver(img);
àààààà}
àààà});
àà}
àà
ààconsole.log('àLazyàLoadingàinitialisiert');
}

/**
à*àFallbackàIntersectionObserveràfüràalteàBrowser
à*/
functionàinitIntersectionObserver(img)à{
ààconstàimageObserverà=ànewàIntersectionObserver((entries,àobserver)à=>à{
ààààentries.forEach(entryà=>à{
ààààààifà(entry.isIntersecting)à{
ààààààààconstàimageà=àentry.target;
àààààààà//àLoadàimageàwennàsichtbar
ààààààààifà(image.srcà||àimage.dataset.src)à{
ààààààààààimage.srcà=àimage.dataset.srcà||àimage.src;
ààààààààààimage.removeAttribute('data-src');
ààààààààààimageObserver.unobserve(image);
àààààààà}
àààààà}
àààà});
àà},à{
ààààrootMargin:à'50pxà0px',
ààààthreshold:à0.01
àà});
àà
ààimageObserver.observe(img);
}

//à===================================================================
//à°àPERFORMANCEàMONITORINGà(optional)
//à===================================================================

/**
à*àLoggtàwichtigeàPerformanceàMetrikenà(nuràinàDevelopment)
à*/
functionàlogPerformanceMetrics()à{
ààifà(document.readyStateà===à'loading')à{
ààààreturn;
àà}

àà//àNutzeàPerformanceàAPIàwennàverfügbar
ààifà(window.performanceà&&àwindow.performance.timing)à{
ààààconstàtimingà=àwindow.performance.timing;
ààààconstàmetricsà=à{
àààààà'DOMàInteractive':àtiming.domInteractiveà-àtiming.navigationStart,
àààààà'DOMàComplete':àtiming.domCompleteà-àtiming.navigationStart,
àààààà'PageàLoadà(onload)':àtiming.loadEventEndà-àtiming.navigationStart,
àààààà'TTIà(Est.)':àtiming.domInteractiveà-àtiming.navigationStart
àààà};
àààà
àààà//àLogànuràwennànichtàinàproduction
ààààifà(window.location.hostnameà===à'localhost'à||àwindow.location.hostnameà===à'127.0.0.1')à{
ààààààconsole.group('°àPerformanceàMetrics');
ààààààObject.entries(metrics).forEach(([label,àms])à=>à{
ààààààààconsole.log(`${label}:à${ms}ms`);
àààààà});
ààààààconsole.groupEnd();
àààà}
àà}

àà//àCumulativeàLayoutàShiftà(CLS)à-àneuereàAPI
ààifà('PerformanceObserver'àinàwindow)à{
ààààtryà{
ààààààconstàobserverà=ànewàPerformanceObserver((list)à=>à{
ààààààààforà(constàentryàofàlist.getEntries())à{
ààààààààààconsole.log('CLSàEntry:',àentry.value);
àààààààà}
àààààà});
ààààààobserver.observe({àentryTypes:à['layout-shift']à});
àààà}àcatchà(e)à{
àààààà//àAPIànotàavailable
àààà}
àà}
}

//à===================================================================
//à°±àSERVICEàWORKERàREGISTRATIONà(optional,àfüràofflineàsupport)
//à===================================================================

/**
à*àRegistriertàServiceWorkeràfüràofflineàFunktionalität
à*àHinweis:àBenötigtàservice-worker.jsàDatei
à*/
functionàregisterServiceWorker()à{
ààifà('serviceWorker'àinànavigator)à{
àààànavigator.serviceWorker.register('service-worker.js')
àààààà.then(registrationà=>à{
ààààààààconsole.log('àServiceàWorkeràregistered:',àregistration);
àààààà})
àààààà.catch(errorà=>à{
ààààààààconsole.log(' —¯¸àServiceàWorkeràregistrationàfailed:',àerror);
àààààà});
àà}
}

//à===================================================================
//à¡àRESOURCEàPRIORITIZATION
//à===================================================================

/**
à*àPreloadàwichtigeàRessourcen
à*/
functionàaddResourceHints()à{
ààconstàheadà=àdocument.head;
àà
àà//àDNSàPrefetchàfüràexterneàRessourcenà(wennàvorhanden)
ààconstàlinksà=à[
àààà//àBeispiel:à{àrel:à'dns-prefetch',àhref:à'https://example.com'à}
àà];
àà
ààlinks.forEach(linkà=>à{
ààààconstàlinkElà=àdocument.createElement('link');
ààààlinkEl.relà=àlink.rel;
ààààlinkEl.hrefà=àlink.href;
ààààhead.appendChild(linkEl);
àà});
}

//à===================================================================
//à°àINITIALIZATION
//à===================================================================

document.addEventListener('DOMContentLoaded',à()à=>à{
ààinitLazyLoading();
ààlogPerformanceMetrics();
ààaddResourceHints();
àà
àà//àDeferredàServiceWorkeràregistrationà(nichtàblocking)
ààifà(document.readyStateà===à'complete')à{
àààà//àregisterServiceWorker();à//àUncommentàwennàservice-worker.jsàexists
àà}àelseà{
ààààwindow.addEventListener('load',à()à=>à{
àààààà//àregisterServiceWorker();
àààà});
àà}
});

//àOderàfrüheràladenàwennàmöglich
ifà(document.readyStateà===à'loading')à{
ààdocument.addEventListener('DOMContentLoaded',àinitLazyLoading);
}àelseà{
ààinitLazyLoading();
}

//à===================================================================
//à°àEXPORT
//à===================================================================

ifà(typeofàmoduleà!==à'undefined'à&&àmodule.exports)à{
ààmodule.exportsà=à{
ààààinitLazyLoading,
ààààlogPerformanceMetrics
àà};
}
