/**
à*àMEDTECHGUIDEà-àREFACTOREDàJAVASCRIPTàARCHITECTURE
à*àModular,àVanillaàJS.àKeinàFramework.àSauberàstrukturiert.
à*àJedeàFunktionàistàunabhängigàinitialisierbar.
à*/

//à================================================================
//à°¾àUTILITYàFUNCTIONS
//à================================================================

/**
à*àDebounce/ThrottleàfüràPerformance-optimierteàEvents
à*à@paramà{Function}àfuncà-àZuàthrottleindeàFunktion
à*à@paramà{number}àdelayà-àmsàVerzögerung
à*à@returnsà{Function}àThrottledàFunktion
à*/
functionàthrottle(func,àdelay)à{
ààletàlastCallà=à0;
ààreturnàfunction(...args)à{
ààààconstànowà=àDate.now();
ààààifà(nowà-àlastCallà>=àdelay)à{
ààààààlastCallà=ànow;
ààààààreturnàfunc(...args);
àààà}
àà};
}

/**
à*àNormalisiertàTextàfüràSucheà(lowercase,àUmlaute,àetc.)
à*à@paramà{string}àtextà-àTextàzumànormalisieren
à*à@returnsà{string}àNormalisierteràText
à*/
functionànormalizeText(text)à{
ààreturnàtext.toLowerCase()
àààà.replace(/ä/g,à'a').replace(/ö/g,à'o').replace(/ü/g,à'u')
àààà.replace(/—/g,à'ss').trim();
}

/**
à*àEntferntàalteàHighlightsàsicher
à*à@paramà{HTMLElement}àcontainerà-àContaineràmitàHighlights
à*/
functionàremoveHighlights(container)à{
ààifà(!container)àreturn;
ààconstàhighlightsà=àcontainer.querySelectorAll'span.highlight');
ààhighlights.forEach(spanà=>à{
ààààconstàparentà=àspan.parentNode;
ààààifà(parent)à{
ààààààwhileà(span.firstChild)à{
ààààààààparent.insertBefore(span.firstChild,àspan);
àààààà}
ààààààparent.removeChild(span);
àààà}
àà});
}

//à================================================================
//à°à1.àLOADERà-àHIDDENàONàPAGEàLOADà(withàfallback)
//à================================================================

functionàinitLoader()à{
àà//àFallback:àLoaderàperàDOMContentLoadedàverstecken
àà//à(wirdàauchàinàHTMLàmitàinlineàscriptàgemacht)
ààwindow.addEventListener('load',à()à=>à{
ààààconstàloaderà=àdocument.getElementById('loader');
ààààifà(!loader)àreturn;
àààà
ààààloader.classList.add('hidden');
ààààsetTimeout(()à=>à{
ààààààloader.style.displayà=à'none';
àààà},à500);
àà});
}

//à================================================================
//à°±àMOBILEàNAVIGATIONà-àRESPONSIVEàLAYOUTà(ohneàHamburgeràToggle)
//à================================================================
//ààANGEPASST:àNavigationàistàjetztàvollàresponsiveàmitàFlexbox
//àToggle-ButtonàwirdàNICHTàmehràbenötigt,àdaàalleàNavigationàElemente
//àimmeràangezeigtàwerdenàundàresponsiveàmitàCSSàreagieren
//à(sieheà.nav-linksàflex-wrapàundàMediaàQueriesàinàstyle.css)

functionàinitMobileNav()à{
àà//àNavigationàistàjetztàvollständigàCSS-responsive
àà//àDieseàFunktionàkannàleeràseinàoderànuràDebuggingàZwecke
ààconsole.log('àResponsiveàNavigationàaktivà(keinàToggleàButtonàbenötigt)');
àà
àà//àNavigationàLinksà-àActiveàManager
ààconstànavLinksà=àdocument.querySelector('.nav-links');
ààifà(!navLinks)àreturn;

àà//àCloseàmenu-likeàbehavioràwennàaufàLinkàgeklicktàwirdà(füràUX)
àà//àKannàaufàzukünftigeàErweiterungenàvorbereitetàsein
àànavLinks.querySelectorAll'a').forEach(linkà=>à{
ààààlink.addEventListener('click',à()à=>à{
àààààà//àOptional:àKannàzukünftigàfüràweitereàFunktionalitätàgenutztàwerden
àààà});
àà});
}

//à================================================================

functionàinitActiveNav()à{
àà//àDefensiveàchecks
ààconstànavLinksà=àdocument.querySelectorAll'.main-navàa');
ààifà(!navLinks.length)àreturn;
àà
àà//àGetàaktuellenàPageàbasierendàaufàpathname
ààconstàcurrentPageà=àwindow.location.pathname.split('/').pop()à||à'index.html';
àà
àànavLinks.forEach(linkà=>à{
ààààconstàhrefà=àlink.getAttribute('href');
àààà//àExakteàoderàrelativeàMatching
ààààifà(hrefà===àcurrentPageà||à
àààààààà(currentPageà===à''à&&àhrefà===à'index.html'))à{
ààààààlink.classList.add('active');
àààà}àelseà{
ààààààlink.classList.remove('active');
àààà}
àà});
}

//à================================================================
//à"—¯¸à3.àSCROLLàTOàTOPàBUTTONà-àPerformanceàoptimiert
//à================================================================

functionàinitScrollToTop()à{
ààconstàscrollBtnà=àdocument.getElementById('scrollToTopBtn');
ààconstànavbarà=àdocument.querySelector('.main-nav');
ààifà(!scrollBtn)àreturn;
àà
àà//àWichtig:àScroll-EventàgeführtàmitàthrottleàumàPerformanceàzuàsparen
ààconstàhandleScrollà=àthrottle(()à=>à{
ààààifà(window.pageYOffsetà>à300)à{
ààààààscrollBtn.classList.add('show');
àààà}àelseà{
ààààààscrollBtn.classList.remove('show');
àààà}
àààà
àààà//àAddàshadowàtoànavbaràwhenàscrolled
ààààifà(navbarà&&àwindow.pageYOffsetà>à50)à{
àààààànavbar.classList.add('scrolled');
àààà}àelseàifà(navbar)à{
àààààànavbar.classList.remove('scrolled');
àààà}
àà},à100);
àà
ààwindow.addEventListener('scroll',àhandleScroll,à{àpassive:àtrueà});
àà
àà//àClickàHandleràfüràButton
ààscrollBtn.addEventListener('click',à()à=>à{
ààààwindow.scrollTo({àtop:à0,àbehavior:à'smooth'à});
àà});
}



//à================================================================
//à¨à5.àSECTIONàFADE-INàANIMATIONSàmitàIntersectionObserver
//à================================================================

functionàinitSectionAnimations()à{
ààconstàsectionsà=àdocument.querySelectorAll'.section-card');
ààifà(!sections.length)àreturn;
àà
àà//àIntersectionObserveràistàperformance-optimiert
ààconstàobserverà=ànewàIntersectionObserver((entries)à=>à{
ààààentries.forEach(entryà=>à{
ààààààifà(entry.isIntersecting)à{
àààààààà//àFadeàinàbeimàSichtbarwerden
ààààààààentry.target.classList.add('fade-in-visible');
àààààààà//àWichtig:àObserveràentfernenànachàAnimationà(memoryàleakàprevention)
ààààààààobserver.unobserve(entry.target);
àààààà}
àààà});
àà},à{
ààààthreshold:à0.1,à//àTriggertàwennà10%àsichtbar
ààààrootMargin:à'0pxà0pxà-50pxà0px'à//àEtwasàfrüheràtriggern
àà});
àà
ààsections.forEach(sectionà=>à{
àààà//àInitialàstate:àinvisible
ààààsection.classList.add('fade-in');
ààààobserver.observe(section);
àà});
}

//à================================================================
//à°à6.àGLOBALàSEARCHàFUNCTION
//à================================================================

functionàinitSearch()à{
àà//àElementàcheck
ààconstàsearchInputà=àdocument.getElementById('globalSearch');
ààifà(!searchInput)àreturn;
àà
ààconstàsearchResultsà=àdocument.getElementById('searchResults');
àà
ààsearchInput.addEventListener('input',à(e)à=>à{
ààààconstàqueryà=àe.target.value.trim();
àààà
àààà//àResetàwennàempty
ààààifà(!query)à{
ààààààifà(searchResults)àsearchResults.innerHTMLà=à'';
ààààààremoveHighlights(document.body);
ààààààreturn;
àààà}
àààà
ààààconstànormalizedQueryà=ànormalizeText(query);
ààààconstàsearchableà=àdocument.querySelectorAll'h1,àh2,àh3,àh4,àp,àli');
àààà
ààààletàhitCountà=à0;
ààààletàfirstHità=ànull;
àààà
àààà//àDurchsucheàalleàElemente
ààààsearchable.forEach(elementà=>à{
ààààààconstàtextà=àelement.textContent;
ààààààconstànormalizedTextà=ànormalizeText(text);
àààààà
ààààààifà(normalizedText.includes(normalizedQuery))à{
àààààààà//àImportante:àNuràEINMALàproàElementàmachen
ààààààààremoveHighlights(element);
àààààààà
ààààààààifà(!firstHit)àfirstHità=àelement;
ààààààààhitCount++;
àààààààà
àààààààà//àHighlightàhinzufügenà(safe)
ààààààààconstàregexà=ànewàRegExp(`(${query})`,à'gi');
ààààààààelement.innerHTMLà=àtext.replace(regex,à'<spanàclass="highlight">$1</span>');
àààààà}àelseà{
ààààààààremoveHighlights(element);
àààààà}
àààà});
àààà
àààà//àScrollàzumàerstenàHit
ààààifà(firstHit)à{
ààààààfirstHit.scrollIntoView({àbehavior:à'smooth',àblock:à'center'à});
àààà}
àààà
àààà//àShowàHitàCount
ààààifà(searchResults)à{
ààààààsearchResults.textContentà=àhitCountà>à0à
àààààààà?à`${hitCount}àTrefferàgefunden`à
àààààààà:à'KeineàTrefferàgefunden';
àààà}
àà});
}

//à================================================================
//à°¨à7.àFILTERàSYSTEMà(füràdevice-cardsàaufàindex.html)
//à================================================================

functionàinitFilters()à{
ààconstàfilterBtnsà=àdocument.querySelectorAll'[data-filter]');
ààconstàdeviceCardsà=àdocument.querySelectorAll'.device-card');
àà
ààifà(!filterBtns.lengthà||à!deviceCards.length)àreturn;
àà
ààfilterBtns.forEach(btnà=>à{
ààààbtn.addEventListener('click',à()à=>à{
ààààààconstàfilterValueà=àbtn.getAttribute('data-filter');
àààààà
àààààà//àUpdateàactiveàbutton
ààààààfilterBtns.forEach(bà=>àb.classList.remove('active'));
ààààààbtn.classList.add('active');
àààààà
àààààà//àFilteràcardsàsmooth
ààààààdeviceCards.forEach(cardà=>à{
ààààààààconstàcardCategoryà=àcard.getAttribute('data-category');
ààààààààconstàshouldShowà=àfilterValueà===à'all'à||àcardCategoryà===àfilterValue;
àààààààà
ààààààààcard.style.transitionà=à'opacityà0.3sàease,àtransformà0.3sàease';
ààààààààcard.style.opacityà=àshouldShowà?à'1'à:à'0.3';
ààààààààcard.style.pointerEventsà=àshouldShowà?à'auto'à:à'none';
àààààà});
àààà});
àà});
}

//à================================================================
//à—¯¸à8.àDEVICEàCOMPARISONàMODALàSYSTEM
//à================================================================

functionàinitCompareSystem()à{
ààconstàcompareToggleà=àdocument.getElementById('compareToggle');
ààconstàcompareCheckboxesà=àdocument.querySelectorAll'[data-compare-checkbox]');
ààconstàcompareBtnà=àdocument.getElementById('compareBtn');
àà
ààifà(!compareCheckboxes.length)àreturn;
àà
àà//àStateàtracking
ààletàselectedDevicesà=à[];
ààconstàMAX_COMPAREà=à2;
ààletàcompareModeActiveà=àfalse;
àà
àà//àToggleàCompareàMode
ààifà(compareToggle)à{
ààààcompareToggle.addEventListener('change',à(e)à=>à{
ààààààcompareModeActiveà=àe.target.checked;
àààààà
ààààààcompareCheckboxes.forEach(checkboxà=>à{
ààààààààcheckbox.style.displayà=àcompareModeActiveà?à'block'à:à'none';
àààààà});
àààààà
ààààààifà(!compareModeActive)à{
àààààààà//àResetàcheckboxesàwennàmodeàausgeschaltet
ààààààààcompareCheckboxes.forEach(cbà=>àcb.checkedà=àfalse);
ààààààààselectedDevicesà=à[];
ààààààààifà(compareBtn)àcompareBtn.disabledà=àtrue;
àààààà}
àààà});
àà}
àà
ààcompareCheckboxes.forEach(checkboxà=>à{
ààààcheckbox.addEventListener('change',à(e)à=>à{
ààààààconstàdeviceNameà=àe.target.getAttribute('data-compare-device');
àààààà
ààààààifà(e.target.checked)à{
àààààààà//àLimitàtoà2
ààààààààifà(selectedDevices.lengthà>=àMAX_COMPARE)à{
ààààààààààe.target.checkedà=àfalse;
ààààààààààalert('Maximalà2àGeräteàzumàVergleichenàauswählbar');
ààààààààààreturn;
àààààààà}
ààààààààselectedDevices.push(deviceName);
àààààà}àelseà{
ààààààààselectedDevicesà=àselectedDevices.filter(dà=>àdà!==àdeviceName);
àààààà}
àààààà
àààààà//àUpdateàButton
ààààààifà(compareBtn)à{
ààààààààcompareBtn.disabledà=àselectedDevices.lengthà<à2;
ààààààààcompareBtn.textContentà=àselectedDevices.lengthà===à2à
àààààààààà?à'Vergleichen'à
àààààààààà:à`Vergleichenà(${selectedDevices.length}/2)`;
àààààà}
àààà});
àà});
àà
àà//àCompareàButtonàHandler
ààifà(compareBtn)à{
ààààcompareBtn.addEventListener('click',à()à=>à{
ààààààifà(selectedDevices.lengthà===à2)à{
ààààààààopenCompareModal(selectedDevices);
àààààà}
àààà});
àà}
}

/**
à*àDeviceàDatenbankàfüràVergleiche
à*/
constàDEVICE_DATABASEà=à{
àà'Diabetes-Technologien':à{
ààààkategorie:à'Therapieà&àMonitoring',
ààààbeschreibung:à'Sensoren,àCGM-Systeme,àInsulinpumpen',
ààààanwendung:à'Diabetes-Management',
ààààverfügbarkeit:à'Weitàverbreitet',
ààààkosten:à'ModeratàbisàHoch',
ààààzukunft:à'KünstlicheàBauchspeicheldrüse'
àà},
àà'Allergiediagnostik':à{
ààààkategorie:à'Diagnostik',
ààààbeschreibung:à'Prick-Tests,àIgE-Bestimmung,àMolekulardiagnostik',
ààààanwendung:à'Allergie-Erkennung',
ààààverfügbarkeit:à'StandardàinàKliniken',
ààààkosten:à'NiedrigàbisàMittel',
ààààzukunft:à'Epikutantestsà&àComponent-Diagnostik'
àà},
àà'Herz-Kreislauf':à{
ààààkategorie:à'Diagnostikà&àTherapie',
ààààbeschreibung:à'EKG,àBlutdruckmessung,àSchrittmacher',
ààààanwendung:à'Herz-Kreislauf-Monitoring',
ààààverfügbarkeit:à'Sehràverbreitet',
ààààkosten:à'Variabelà(niedrigàbisàsehràhoch)',
ààààzukunft:à'DrahtloseàImplantate'
àà},
àà'Bildgebung':à{
ààààkategorie:à'Diagnostik',
ààààbeschreibung:à'Röntgen,àCT,àMRT,àUltraschall',
ààààanwendung:à'BildgebendesàVerfahren',
ààààverfügbarkeit:à'InàallenàKliniken',
ààààkosten:à'Hochà(MRT/CT)',
ààààzukunft:à'Hochauflösungs-KI-Analyse'
àà},
àà'Neurochips':à{
ààààkategorie:à'Forschungà&àTherapie',
ààààbeschreibung:à'Brain-ComputeràInterfaces,àtiefeàHirnstimulation',
ààààanwendung:à'Neuromodulation',
ààààverfügbarkeit:à'Experimentalà/àBegrenzt',
ààààkosten:à'SehràHoch',
ààààzukunft:à'BidirektionaleàNeural-Recording'
àà},
àà'Exoskelette':à{
ààààkategorie:à'Therapieà&àRehabilitation',
ààààbeschreibung:à'RoboterassistenzàinàBewegung',
ààààanwendung:à'Rehabilitation,àIndustrie',
ààààverfügbarkeit:à'ZunehmendàinàKliniken',
ààààkosten:à'Hoch',
ààààzukunft:à'Brain-gesteuerteàExoskelette'
àà},
àà'Genetik':à{
ààààkategorie:à'Forschungà&àTherapie',
ààààbeschreibung:à'CRISPR,àDNA-Sequenzierung',
ààààanwendung:à'Genanalyseà&àGentherapie',
ààààverfügbarkeit:à'BegrenztàaufàspezialisierteàZentren',
ààààkosten:à'Sinkendà(Sequenzierung)',
ààààzukunft:à'In-vivoàCRISPR-Therapien'
àà},
àà'KI-Diagnose':à{
ààààkategorie:à'Zukunftstechnologie',
ààààbeschreibung:à'KünstlicheàIntelligenzàfüràAnalyse',
ààààanwendung:à'Bildanalyse,àDiagnostik',
ààààverfügbarkeit:à'ZunehmendàinàRadiologie',
ààààkosten:à'Variable',
ààààzukunft:à'VollautomatisierteàDiagnose'
àà},
àà'Zukunftstechnologien':à{
ààààkategorie:à'Forschung',
ààààbeschreibung:à'Nano-Medizin,àBio-Interfaces',
ààààanwendung:à'Experimentell',
ààààverfügbarkeit:à'Nichtài.d.R.àverfügbar',
ààààkosten:à'R&DàPhase',
ààààzukunft:à'KörpereigeneàNanotechnik'
àà}
};

/**
à*àÖffnetàModalàmitàVergleichàzweieràGeräte
à*à@paramà{Array}àdevicesà-àzweiàzuàvergleichendeàGeräte
à*/
functionàopenCompareModal(devices)à{
àà//àStelleàsicheràdassàbeideàGeräteàexistieren
ààconstàdevice1à=àDEVICE_DATABASE[devices[0]];
ààconstàdevice2à=àDEVICE_DATABASE[devices[1]];
àà
ààifà(!device1à||à!device2)à{
ààààconsole.warn('EinàoderàbeideàGeräteànichtàinàDatenbankàgefunden');
ààààreturn;
àà}
àà
àà//àErstelleàVergleichstabelle
ààconstàtableHTMLà=à`
àààà<tableàclass="device-comparison-table">
àààààà<thead>
àààààààà<tr>
àààààààààà<th>Eigenschaft</th>
àààààààààà<th>${devices[0]}</th>
àààààààààà<th>${devices[1]}</th>
àààààààà</tr>
àààààà</thead>
àààààà<tbody>
àààààààà<tr>
àààààààààà<td><strong>Kategorie</strong></td>
àààààààààà<td>${device1.kategorie}</td>
àààààààààà<td>${device2.kategorie}</td>
àààààààà</tr>
àààààààà<tr>
àààààààààà<td><strong>Beschreibung</strong></td>
àààààààààà<td>${device1.beschreibung}</td>
àààààààààà<td>${device2.beschreibung}</td>
àààààààà</tr>
àààààààà<tr>
àààààààààà<td><strong>Anwendungsgebiet</strong></td>
àààààààààà<td>${device1.anwendung}</td>
àààààààààà<td>${device2.anwendung}</td>
àààààààà</tr>
àààààààà<tr>
àààààààààà<td><strong>Verfügbarkeit</strong></td>
àààààààààà<td>${device1.verfügbarkeit}</td>
àààààààààà<td>${device2.verfügbarkeit}</td>
àààààààà</tr>
àààààààà<tr>
àààààààààà<td><strong>Kostenbereich</strong></td>
àààààààààà<td>${device1.kosten}</td>
àààààààààà<td>${device2.kosten}</td>
àààààààà</tr>
àààààààà<tr>
àààààààààà<td><strong>Zukunftsperspektive</strong></td>
àààààààààà<td>${device1.zukunft}</td>
àààààààààà<td>${device2.zukunft}</td>
àààààààà</tr>
àààààà</tbody>
àààà</table>
àà`;
àà
àà//àErstelleàModal
ààconstàmodalà=àdocument.createElement('div');
ààmodal.classNameà=à'compare-modal';
ààmodal.setAttribute('aria-hidden',à'false');
ààmodal.setAttribute('role',à'dialog');
àà
ààmodal.innerHTMLà=à`
àààà<divàclass="compare-modal-overlay"></div>
àààà<divàclass="compare-modal-content">
àààààà<buttonàclass="modal-close"àaria-label="Modalàschlie—en"></button>
àààààà<h2>Vergleich:à${devices[0]}àvsà${devices[1]}</h2>
àààààà<divàclass="compare-table">
àààààààà${tableHTML}
àààààà</div>
àààà</div>
àà`;
àà
ààdocument.body.appendChild(modal);
àà
àà//àCloseàHandler
ààconstàcloseBtnà=àmodal.querySelector('.modal-close');
ààconstàoverlayà=àmodal.querySelector('.compare-modal-overlay');
àà
ààconstàcloseModalà=à()à=>à{
ààààmodal.classList.add('fade-out');
ààààsetTimeout(()à=>àmodal.remove(),à300);
àà};
àà
ààcloseBtn.addEventListener('click',àcloseModal);
ààoverlay.addEventListener('click',àcloseModal);
àà
àà//àESCàkeyàzumàSchlie—en
ààconstàhandleEscà=à(e)à=>à{
ààààifà(e.keyà===à'Escape')à{
ààààààcloseModal);
ààààààdocument.removeEventListener('keydown',àhandleEsc);
àààà}
àà};
ààdocument.addEventListener('keydown',àhandleEsc);
}

//à================================================================
//à°ç à9.àGLOSSARYàTOOLTIPàSYSTEMà(Automatisch)
//à================================================================

functionàinitGlossaryTooltips()à{
ààconstàglossaryTermsà=àdocument.querySelectorAll'.glossar-termàdt');
ààifà(!glossaryTerms.length)àreturn;
àà
àà//àSammleàalleàGlossar-Begriffe
ààconstàglossaryDataà=à{};
ààglossaryTerms.forEach(dtà=>à{
ààààconstàtermà=àdt.textContent.trim();
ààààconstàdefinitionà=àdt.nextElementSibling?.textContent?.trim()à||à'';
ààààglossaryData[term]à=àdefinition;
àà});
àà
àà//àDurchsucheàSeiteànachàGlossar-Begriffen
ààconstàwalkerà=àdocument.createTreeWalker(
ààààdocument.body,
ààààNodeFilter.SHOW_TEXT,
àààànull,
ààààfalse
àà);
àà
ààconstànodesToReplaceà=à[];
ààletànode;
àà
ààwhileà(nodeà=àwalker.nextNode())à{
àààànodesToReplace.push(node);
àà}
àà
àànodesToReplace.forEach(textNodeà=>à{
ààààletàcontentà=àtextNode.textContent;
ààààletàhasMatchà=àfalse;
àààà
ààààObject.keys(glossaryData).forEach(termà=>à{
ààààààifà(content.toLowerCase().includes(term.toLowerCase()))à{
ààààààààhasMatchà=àtrue;
ààààààààconstàregexà=ànewàRegExp(`\\b${term}\\b`,à'gi');
ààààààààcontentà=àcontent.replace(regex,à`<spanàclass="glossary-link"àdata-term="${term}">$&</span>`);
àààààà}
àààà});
àààà
ààààifà(hasMatch)à{
ààààààconstàspanà=àdocument.createElement('span');
ààààààspan.innerHTMLà=àcontent;
ààààààtextNode.parentNode.replaceChild(span,àtextNode);
àààà}
àà});
àà
àà//àEventàHandleràfüràTooltips
ààdocument.addEventListener('mouseenter',à(e)à=>à{
ààààifà(e.target.classList.contains('glossary-link'))à{
ààààààconstàtermà=àe.target.getAttribute('data-term');
ààààààconstàdefinitionà=àglossaryData[term];
àààààà
ààààààshowGlossaryTooltip(e.target,àdefinition);
àààà}
àà},àtrue);
}

/**
à*àZeigtàGlossar-Tooltipàan
à*à@paramà{Element}àelementà-àElementàmitàTooltip
à*à@paramà{string}àdefinitionà-àDefinitionàzumàAnzeigen
à*/
functionàshowGlossaryTooltip(element,àdefinition)à{
àà//àOldàTooltipàentfernen
ààconstàoldTooltipà=àdocument.querySelector('.glossary-tooltip');
ààifà(oldTooltip)àoldTooltip.remove();
àà
ààconstàtooltipà=àdocument.createElement('div');
ààtooltip.classNameà=à'glossary-tooltip';
ààtooltip.textContentà=àdefinition;
ààtooltip.setAttribute('role',à'tooltip');
àà
ààdocument.body.appendChild(tooltip);
àà
àà//àPositionàTooltip
ààconstàrectà=àelement.getBoundingClientRect();
ààtooltip.style.topà=à(rect.topà-àtooltip.offsetHeightà-à10)à+à'px';
ààtooltip.style.leftà=à(rect.leftà+àrect.widthà/à2à-àtooltip.offsetWidthà/à2)à+à'px';
àà
àà//àRemoveàonàmouseleave
ààelement.addEventListener('mouseleave',à()à=>à{
ààààtooltip.remove();
àà},à{àonce:àtrueà});
}

//à================================================================
//à°àINITIALIZATIONà-àDocumentàReadyàEvent
//à================================================================

//àRelatedàLinksàDataà(füràThemenseiten)
constàrelatedLinksDataà=à{
ààdiabetes:à[
àààà["InternationalàDiabetesàFederation",à"https://idf.org/"],
àààà["DeutscheàDiabetesàGesellschaft",à"https://www.deutsche-diabetes-gesellschaft.de/"],
àààà["AmericanàDiabetesàAssociation",à"https://www.diabetes.org/"],
àààà["WHOà-àDiabetes",à"https://www.who.int/health-topics/diabetes"],
àààà["CDCà-àDiabetes",à"https://www.cdc.gov/diabetes/"],
àààà["NIHà-àDiabetesàResearch",à"https://www.niddk.nih.gov/"]
àà],
ààallergie:à[
àààà["ÖsterreichischeàGesellschaftàfüràAllergologie",à"https://www.oegaai.at/"],
àààà["DeutscheàGesellschaftàfüràAllergologieàundàklinischeàImmunologie",à"https://www.dgaki.de/"],
àààà["AmericanàAcademyàofàAllergy,àAsthmaà&àImmunology",à"https://www.aaaai.org/"],
àààà["WHOà-àAllergies",à"https://www.who.int/"],
àààà["PollenwarndienstàEuropa",à"https://www.pollenwarndienst.at/"],
àààà["Allergyà&àAsthmaàNetwork",à"https://www.allergyasthmanetwork.org/"]
àà],
ààherz:à[
àààà["DeutscheàHerzstiftung",à"https://www.herzstiftung.de/"],
àààà["AmericanàHeartàAssociation",à"https://www.heart.org/"],
àààà["EuropeanàHeartàRhythmàAssociation",à"https://www.ehra.org/"],
àààà["BritishàHeartàFoundation",à"https://www.bhf.org.uk/"],
àààà["MayoàClinicà-àHeartàDiseases",à"https://www.mayoclinic.org/diseases-conditions/heart-disease/"],
àààà["NIHà-àHeartàInstitute",à"https://www.nhlbi.nih.gov/"]
àà],
ààbildgebung:à[
àààà["Radiopaediaà-àMedicalàImaging",à"https://radiopaedia.org/"],
àààà["EuropeanàSocietyàofàRadiology",à"https://www.myesr.org/"],
àààà["AmericanàCollegeàofàRadiology",à"https://www.acr.org/"],
àààà["MRIàExplained",à"https://mriexplained.com/"],
àààà["FDAà-àMedicalàImaging",à"https://www.fda.gov/radiation-emitting-products/"],
àààà["Natureà-àMedicalàImagingàResearch",à"https://www.nature.com/"]
àà],
ààneurochips:à[
àààà["BCIàSociety",à"https://www.bci-info.org/"],
àààà["NeuralinkàPublicàInformation",à"https://neuralink.com/"],
àààà["Brain-ComputeràInterfacesà-àTUàGraz",à"https://bci.tugraz.at/"],
àààà["FrontiersàinàNeuroscience",à"https://www.frontiersin.org/journals/neuroscience/"],
àààà["NINDSà-àBrainàResearch",à"https://www.ninds.nih.gov/"],
àààà["NatureàNeuroscience",à"https://www.nature.com/articles/s41593-021-00928-z"]
àà],
ààexoskelette:à[
àààà["ExoskeletonàReport",à"https://exoskeletonreport.com/"],
àààà["ReWalkàRobotics",à"https://rewalk.com/"],
àààà["EksoàBionics",à"https://eksobionics.com/"],
àààà["ScienceDirectà-àExoskeletons",à"https://www.sciencedirect.com/topics/engineering/exoskeleton"],
àààà["IEEEà-àRoboticsà&àAutomation",à"https://www.ieee.org/"],
àààà["WearableàRoboticsà-àResearch",à"https://www.frontiersin.org/"]
àà],
ààgenetik:à[
àààà["Genome.govà-àNIH",à"https://www.genome.gov/"],
àààà["LearnàGeneticsà-àUniversityàofàUtah",à"https://learn.genetics.utah.edu/"],
àààà["YourGenomeà-àWellcomeàSangeràInstitute",à"https://www.yourgenome.org/"],
àààà["NatureàGenetics",à"https://www.nature.com/subjects/genetics"],
àààà["CRISPRàGeneàEditingàDatabase",à"https://www.ebi.ac.uk/"],
àààà["AmericanàSocietyàofàHumanàGenetics",à"https://www.ashg.org/"]
àà],
ààki:à[
àààà["AIàinàHealthcareà-àStanford",à"https://aihealth.stanford.edu/"],
àààà["WHOà-àAIàGuidelinesàforàHealth",à"https://www.who.int/publications/i/item/9789240029200"],
àààà["NatureàMachineàIntelligence",à"https://www.nature.com/subjects/machine-learning"],
àààà["OpenAIà-àResearchàonàAIàSafety",à"https://openai.com/research/"],
àààà["MITà-àAIàforàHealthcare",à"https://dspace.mit.edu/"],
àààà["IEEEàXploreà-àAIàinàMedicine",à"https://ieeexplore.ieee.org/"]
àà],
ààzukunft:à[
àààà["MITàTechnologyàReviewà-àHealthcare",à"https://www.technologyreview.com/topic/health/"],
àààà["WHOà-àDigitalàHealth",à"https://www.who.int/health-topics/digital-health"],
àààà["Natureà-àMedicalàResearch",à"https://www.nature.com/subjects/medical-research"],
àààà["NIHà-àMedicalàResearch",à"https://www.nih.gov/"],
àààà["EUàDigitalàHealthàPolicy",à"https://ec.europa.eu/health/"],
àààà["Sciencedailyà-àMedicalàNews",à"https://www.sciencedaily.com/"]
àà]
};

/**
à*àSetteràfüràRelatedàLinksà(füràThemenseiten)
à*à@paramà{string}àtopicà-àTopicàKeyà(z.B.à'diabetes')
à*/
functionàsetRelatedLinks(topic)à{
ààconstàlinksà=àrelatedLinksData[topic];
ààconstàrelatedLinksContainerà=àdocument.getElementById('related-links');
àà
ààifà(!linksà||à!relatedLinksContainer)àreturn;
àà
ààrelatedLinksContainer.innerHTMLà=à'';
àà
ààlinks.forEach(([title,àurl])à=>à{
ààààconstàlià=àdocument.createElement('li');
ààààconstàaà=àdocument.createElement('a');
ààààa.hrefà=àurl;
ààààa.textContentà=àtitle;
ààààa.targetà=à'_blank';
ààààa.relà=à'noopenerànoreferrer';
ààààli.appendChild(a);
ààààrelatedLinksContainer.appendChild(li);
àà});
}

/**
à*àBackwardàCompatibilityàAliasàfüràalteàCode
à*/
functionàsetActiveNavLink()à{
ààinitActiveNav();
}

document.addEventListener('DOMContentLoaded',à()à=>à{
àà//àInitialisiereàalleàModuleàderàReiheànach
ààinitLoader();àààààààà//àLoaderàverstecken
ààinitMobileNav();ààààà//àMobileàMenü
ààinitActiveNav();ààààà//àNavigationàhighlighting
ààinitScrollToTop();ààà//àScrollàtoàTopàButton
ààinitSectionAnimations();à//àFade-InàAnimations
ààinitSearch();àààààààà//àGlobaleàSuche
ààinitFilters();ààààààà//àFilteràSystem
ààinitCompareSystem();à//àVergleichàModal
ààinitGlossaryTooltips();à//àGlossaràTooltips
});
