/**
à*à=====================================================
à*àADHS-TESTà-àModul
à*àStrukturierteràADHS-Screening-Testà(Jugendlicheà&àErwachsene)
à*àOrientierung:àDSM-5-Symptomcluster
à*à=====================================================
à*/

constàADHSTestà=à{
ààtestId:à'adhs',
ààtestName:à'ADHS-Test',
ààtestDescription:à'ADHS-ScreeningàfüràJugendlicheà&àErwachseneà(40àFragen)',

àà//à5-stufigeàAntwortskalaàfüràmehràDifferenzierung
ààanswerOptions:à[
àààà{àvalue:à0,àlabel:à'Nie',àcolor:à'#22c55e'à},
àààà{àvalue:à1,àlabel:à'Selten',àcolor:à'#84cc16'à},
àààà{àvalue:à2,àlabel:à'Manchmal',àcolor:à'#f59e0b'à},
àààà{àvalue:à3,àlabel:à'Häufig',àcolor:à'#f97316'à},
àààà{àvalue:à4,àlabel:à'Sehràhäufig',àcolor:à'#ef4444'à}
àà],

àà//à40àFragenàzuàdenà5àProblembereichenà(8àproàBereich)
ààquestions:à[
àààà//à===àUNAUFMERKSAMKEITà(8àFragen)à===
àààà{àid:à1,àcategory:à'Unaufmerksamkeit',àsubcategory:à'Unaufmerksamkeit',àquestion:à'IchàhabeàSchwierigkeiten,àaufàDetailsàzuàachten.'à},
àààà{àid:à2,àcategory:à'Unaufmerksamkeit',àsubcategory:à'Unaufmerksamkeit',àquestion:à'Miràfälltàesàschwer,àmichàüberàlängereàZeitàaufàAufgabenàzuàkonzentrieren.'à},
àààà{àid:à3,àcategory:à'Unaufmerksamkeit',àsubcategory:à'Unaufmerksamkeit',àquestion:à'IchàverliereàleichtàdenàFadenàbeiàGesprächenàoderàbeimàLesen.'à},
àààà{àid:à4,àcategory:à'Unaufmerksamkeit',àsubcategory:à'Unaufmerksamkeit',àquestion:à'WichtigeàAufgabenàbleibenàunvollständig,àweilàichàmichànichtàkonzentrierenàkann.'à},
àààà{àid:à5,àcategory:à'Unaufmerksamkeit',àsubcategory:à'Unaufmerksamkeit',àquestion:à'Ichàwerdeàleichtàdurchàäu—ereàReizeàabgelenkt.'à},
àààà{àid:à6,àcategory:à'Unaufmerksamkeit',àsubcategory:à'Unaufmerksamkeit',àquestion:à'Miràistàesàschwer,àAnweisungenàzuàfolgen.'à},
àààà{àid:à7,àcategory:à'Unaufmerksamkeit',àsubcategory:à'Unaufmerksamkeit',àquestion:à'IchàvergesseàhäufigàalltäglicheàAufgabenàoderàVerpflichtungen.'à},
àààà{àid:à8,àcategory:à'Unaufmerksamkeit',àsubcategory:à'Unaufmerksamkeit',àquestion:à'IchàmacheàFlüchtigkeitsfehleràbeiàderàArbeitàoderàinàderàSchule.'à},

àààà//à===àHYPERAKTIVITÄTà(8àFragen)à===
àààà{àid:à9,àcategory:à'Hyperaktivität',àsubcategory:à'Hyperaktivität',àquestion:à'IchàbinàständigàinàBewegungàoderàkannàschweràstillsitzen.'à},
àààà{àid:à10,àcategory:à'Hyperaktivität',àsubcategory:à'Hyperaktivität',àquestion:à'IchàzappeleàmitàmeinenàHändenàoderàFü—en.'à},
àààà{àid:à11,àcategory:à'Hyperaktivität',àsubcategory:à'Hyperaktivität',àquestion:à'IchàverlasseàoftàmeinenàSitz,àwennàichàsitzenàsollte.'à},
àààà{àid:à12,àcategory:à'Hyperaktivität',àsubcategory:à'Hyperaktivität',àquestion:à'IchàkannàschweràruhigeàAktivitätenàausführen.'à},
àààà{àid:à13,àcategory:à'Hyperaktivität',àsubcategory:à'Hyperaktivität',àquestion:à'IchàfühleàmichàinnereàUnruheàoderàRastlosigkeit.'à},
àààà{àid:à14,àcategory:à'Hyperaktivität',àsubcategory:à'Hyperaktivität',àquestion:à'Ichàredeàmehràalsàandereàoderàesàfälltàmiràschweràzuàschweigen.'à},
àààà{àid:à15,àcategory:à'Hyperaktivität',àsubcategory:à'Hyperaktivität',àquestion:à'Ichàbinàimpulsivàdabei,àmichàaufàAktivitätenàeinzulassen.'à},
àààà{àid:à16,àcategory:à'Hyperaktivität',àsubcategory:à'Hyperaktivität',àquestion:à'Ichàbinàständigà"inàAktion"àoderà"aufàSparflammen".'à},

àààà//à===àIMPULSIVITÄTà(8àFragen)à===
àààà{àid:à17,àcategory:à'Impulsivität',àsubcategory:à'Impulsivität',àquestion:à'IchàsageàoderàmacheàDinge,àohneànachzudenken.'à},
àààà{àid:à18,àcategory:à'Impulsivität',àsubcategory:à'Impulsivität',àquestion:à'IchàschneideàanderenàimàGesprächàdasàWortàab.'à},
àààà{àid:à19,àcategory:à'Impulsivität',àsubcategory:à'Impulsivität',àquestion:à'IchàhabeàSchwierigkeiten,àzuàwarten,àbisàichàdranàbin.'à},
àààà{àid:à20,àcategory:à'Impulsivität',àsubcategory:à'Impulsivität',àquestion:à'IchàtreffeàichàschnelleàEntscheidungen,àdieàichàspäteràbereue.'à},
àààà{àid:à21,àcategory:à'Impulsivität',àsubcategory:à'Impulsivität',àquestion:à'Ichàbinàleichtàreizbaràoderàtemperamentvoll.'à},
àààà{àid:à22,àcategory:à'Impulsivität',àsubcategory:à'Impulsivität',àquestion:à'IchàhandleàohneàdieàKonsequenzenàzuàbedenken.'à},
àààà{àid:à23,àcategory:à'Impulsivität',àsubcategory:à'Impulsivität',àquestion:à'MeineàStimmungàwechseltàschnellàundàheftig.'à},
àààà{àid:à24,àcategory:à'Impulsivität',àsubcategory:à'Impulsivität',àquestion:à'IchàplatzeàoftàmitàAntwortenàheraus,àohneàabzuwarten.'à},

àààà//à===àORGANISATIONSPROBLEMEà(8àFragen)à===
àààà{àid:à25,àcategory:à'Organisation',àsubcategory:à'Organisationsprobleme',àquestion:à'Miràfälltàesàschwer,àzuàplanenàundàzuàorganisieren.'à},
àààà{àid:à26,àcategory:à'Organisation',àsubcategory:à'Organisationsprobleme',àquestion:à'IchàverliereàhäufigàwichtigeàGegenständeà(Schlüssel,àDokumente,àetc.).'à},
àààà{àid:à27,àcategory:à'Organisation',àsubcategory:à'Organisationsprobleme',àquestion:à'MeinàArbeitsplatzàoderàZimmeràistàchaotischàundàunorganisiert.'à},
àààà{àid:à28,àcategory:à'Organisation',àsubcategory:à'Organisationsprobleme',àquestion:à'Miràfälltàesàschwer,àFristenàeinzuhalten.'à},
àààà{àid:à29,àcategory:à'Organisation',àsubcategory:à'Organisationsprobleme',àquestion:à'IchàvergesseàTermineàundàVerpflichtungen.'à},
àààà{àid:à30,àcategory:à'Organisation',àsubcategory:à'Organisationsprobleme',àquestion:à'IchàhabeàSchwierigkeiten,àmehrstufigeàAufgabenàzuàstrukturieren.'à},
àààà{àid:à31,àcategory:à'Organisation',àsubcategory:à'Organisationsprobleme',àquestion:à'Ichàprokrastiniereàhäufig.'à},
àààà{àid:à32,àcategory:à'Organisation',àsubcategory:à'Organisationsprobleme',àquestion:à'IchàkannàkeineàPrioritätenàsetzen.'à},

àààà//à===àALLTAGSBEEINTRÄCHTIGUNGà(8àFragen)à===
àààà{àid:à33,àcategory:à'Alltagsauswirkungen',àsubcategory:à'Alltagsbeeinträchtigung',àquestion:à'DieseàSymptomeàbeeinträchtigenàmeineàschulischeàoderàberuflicheàLeistung.'à},
àààà{àid:à34,àcategory:à'Alltagsauswirkungen',àsubcategory:à'Alltagsbeeinträchtigung',àquestion:à'DieseàSymptomeàbeeinträchtigenàmeineàsozialenàBeziehungen.'à},
àààà{àid:à35,àcategory:à'Alltagsauswirkungen',àsubcategory:à'Alltagsbeeinträchtigung',àquestion:à'DieseàSymptomeàbeeinträchtigenàmeineàFamilieàundàmeinàZuhause.'à},
àààà{àid:à36,àcategory:à'Alltagsauswirkungen',àsubcategory:à'Alltagsbeeinträchtigung',àquestion:à'DieseàSymptomeàbeeinträchtigenàmeineàFreizeitàundàHobbys.'à},
àààà{àid:à37,àcategory:à'Alltagsauswirkungen',àsubcategory:à'Alltagsbeeinträchtigung',àquestion:à'IchàfühleàmichàinàmeinenàFähigkeitenàbeeinträchtigt.'à},
àààà{àid:à38,àcategory:à'Alltagsauswirkungen',àsubcategory:à'Alltagsbeeinträchtigung',àquestion:à'MeinàSelbstvertrauenàleidetàunteràdiesenàSymptomen.'à},
àààà{àid:à39,àcategory:à'Alltagsauswirkungen',àsubcategory:à'Alltagsbeeinträchtigung',àquestion:à'Ichàvermute,àdassàdieseàSymptomeàvermutlichàschonàseitàmeineràKindheitàbestehen.'à},
àààà{àid:à40,àcategory:à'Alltagsauswirkungen',àsubcategory:à'Alltagsbeeinträchtigung',àquestion:à'MeineàFamilieàoderàengeàPersonenàhabenàmiràschonàgesagt,àdassàichàdieseàSymptomeàzeige.'à}
àà],

àà/**
ààà*àBerechnetàSubscoresàfüràjedeàKategorie
ààà*/
ààcalculateSubscores(answers)à{
ààààconstàcategoriesà=à{};
ààààthis.questions.forEach(qà=>à{
ààààààifà(!categories[q.subcategory])à{
ààààààààcategories[q.subcategory]à=à0;
àààààà}
ààààààcategories[q.subcategory]à+=àanswers[q.id]à||à0;
àààà});
ààààreturnàcategories;
àà},

àà/**
ààà*àBerechnetàGesamtscoreà(0-160)
ààà*/
ààcalculateScore(answers)à{
ààààreturnàObject.values(answers).reduce((sum,àval)à=>àsumà+à(valà||à0),à0);
àà},

àà/**
ààà*àLiefertàdieàInterpretationàdesàScores
ààà*/
ààgetInterpretation(score)à{
ààààifà(scoreà<=à32)à{
ààààààreturnà{
ààààààààlevel:à'Gering',
ààààààààcolor:à'#22c55e',
ààààààààdescription:à'GeringeàSymptomausprägung',
ààààààààtext:à'IhreàAntwortenàdeutenàaufàgeringeàADHS-Symptomeàhin.'
àààààà};
àààà}àelseàifà(scoreà<=à64)à{
ààààààreturnà{
ààààààààlevel:à'Leicht-Moderat',
ààààààààcolor:à'#f59e0b',
ààààààààdescription:à'LeichtàbisàmoderateàSymptomausprägung',
ààààààààtext:à'Sieàzeigenàleichtàbisàmä—igàausgeprägteàADHS-Symptome.àProfessionelleàEvaluationàwirdàempfohlen.'
àààààà};
àààà}àelseàifà(scoreà<=à96)à{
ààààààreturnà{
ààààààààlevel:à'Moderat-Schwer',
ààààààààcolor:à'#f97316',
ààààààààdescription:à'Mä—igàbisàschwereàSymptomausprägung',
ààààààààtext:à'IhreàSymptomeàsindàdeutlich.àProfessionelleàUnterstützungàwirdàdringendàempfohlen.'
àààààà};
àààà}àelseà{
ààààààreturnà{
ààààààààlevel:à'Schwer',
ààààààààcolor:à'#ef4444',
ààààààààdescription:à'SchwereàSymptomausprägung',
ààààààààtext:à'SieàzeigenàerheblicheàADHS-Symptome.àEineàpsychiatrischeàBewertungàdurchàeinenàFachmannàwirdàdringendàempfohlen.'
àààààà};
àààà}
àà},

àà/**
ààà*àMedizinischeràHinweis
ààà*/
ààmedicalDisclaimer:à`
àààà<divàstyle="background:à#fef2f2;àborder-left:à4pxàsolidà#ef4444;àpadding:à1rem;àmargin-top:à2rem;àborder-radius:à8px;">
àààààà<pàstyle="margin:à0;àfont-weight:à600;àcolor:à#7f1d1d;"> —¯¸àWichtigeràHinweis:</p>
àààààà<pàstyle="margin:à0.5remà0à0à0;àcolor:à#5f3738;àfont-size:à0.95rem;">
ààààààààDieseràTestàdientànuràzuràgrobenàOrientierungàundàersetztàkeineàmedizinischeàDiagnose.àBeiàanhaltendenàoderàbelastendenàBeschwerdenàwendenàSieàsichàbitteàanàeineàÄrztin,àeinenàArztàoderàeineàpsychologischeàFachperson.
àààààà</p>
àààà</div>
àà`
};
