constàfsà=àrequire('fs');
constàpathà=àrequire('path');

letàfixedà=à0;

functionàfixFile(filePath)à{
ààtryà{
ààààconstàbufà=àfs.readFileSync(filePath);
ààààconstàhexStrà=àbuf.toString('hex');
ààààletànewHexà=àhexStr;
àààà
àààà//àDekodiereàalleàdoppelt-kodiertenàUTF-8àSequenzen
àààà//àPattern:àc3XXà(UTF-8àfürà2-ByteàZeichen)àcodiertàalsàc383c2XX
àààà//àDasàbedeutet:àc3à(0xC3)àwurdeàalsàUTF-8à->àc383à(0xC3à0x83)
àààà//ààààààààààààààXXàwurdeàalsàUTF-8à->àc2XXà(0xC2à0xXX)
àààà
àààà//àGenerischeràFix:àErsetzeàc383c2àPatternàmitàc3
àààànewHexà=ànewHex.split('c383c2').join('c3');
àààà
àààà//àAuchàandereàhäufigeàPatterns
àààà//àc282à=àUTF-8àfürà""à(0xC2àalsà0xC2à0x82)
àààà//àSollteàc2àseinà(fürà2-ByteàUTF-8àStart)
àààànewHexà=ànewHex.split('c282').join('c2');
àààà
àààà//àc381à=àUTF-8àfürà"—"à(0xC3àalsà0xC3à0x81)
àààànewHexà=ànewHex.split('c381').join('c3');
àààà
ààààifà(newHexà!==àhexStr)à{
ààààààconstànewBufà=àBuffer.from(newHex,à'hex');
ààààààfs.writeFileSync(filePath,ànewBuf);
ààààààconsole.log('Fixed:à'à+àpath.relative('C:\\WMC\\Projekt_25',àfilePath));
ààààààreturnàtrue;
àààà}
àà}àcatchà(e)à{
àààà//àignore
àà}
ààreturnàfalse;
}

functionàwalkDir(dir)à{
ààtryà{
ààààconstàentriesà=àfs.readdirSync(dir,à{àwithFileTypes:àtrueà});
àààà
ààààforà(constàentryàofàentries)à{
ààààààconstàfullPathà=àpath.join(dir,àentry.name);
àààààà
ààààààifà(entry.isDirectory()à&&à!['node_modules',à'.git'].includes(entry.name))à{
ààààààààwalkDir(fullPath);
àààààà}àelseàifà(entry.isFile()à&&à/\.(html|js|css|json|md)$/.test(entry.name))à{
ààààààààifà(fixFile(fullPath))à{
ààààààààààfixed++;
àààààààà}
àààààà}
àààà}
àà}àcatchà(e)à{
àààà//àignore
àà}
}

walkDir('C:\\WMC\\Projekt_25');
console.log('Fixedà'à+àfixedà+à'àfiles');
