constàfsà=àrequire('fs');
constàpathà=àrequire('path');

letàfixedà=à0;

functionàfixFile(filePath)à{
ààtryà{
àààà//àLeseàalsàBinary,àdekodiereàalsàUTF-8à(wasàdieàdoppelt-kodiertenàBytesàenthält)
ààààconstàbufà=àfs.readFileSync(filePath);
ààààletàutf8strà=àbuf.toString('utf8');
àààà
àààà//àDieseàFunktionàversucht,àdoppelt-kodierteàUTF-8àzurückzuwandeln
àààà//àWennàUTF-8àalsàUTF-8àdoppeltàkodiertàwurde,àsehenàwiràZeichenàwieà"à"à(0xC3à0x20àinàUTF-8à=à0xC3,à0xA4àinàOriginal)
àààà
àààà//àKonvertiereàUTF-8-StringàzurückàzuàBytesàundàreinterpretiere
ààààconstàbytesà=àBuffer.from(utf8str,à'utf8');
ààààletàfixedstrà=à'';
àààà
ààààletàià=à0;
ààààwhileà(ià<àbytes.length)à{
ààààààconstàbà=àbytes[i];
àààààà
àààààà//àWennàwiràeinàUTF-8àMulti-ByteàPrefixà(0xC0-0xFE)àsehen,àaberàdasànächsteàByte
àààààà//àkeinàContinuation-Byteà(0x80-0xBF)àist,àdannàistàesàwahrscheinlichàeineàfehlerhafte
àààààà//àSequenzàdieàalsàeinzelneàBytesàinterpretiertàwerdenàsollte
àààààà
ààààààifà((bà&à0xC0)à===à0xC0à&&àià+à1à<àbytes.length)à{
ààààààààconstàb2à=àbytes[ià+à1];
àààààààà//àWennàdasànächsteàByteàauchàeinàStartbyteàist,àdannàwaràdasàOriginalàwahrscheinlich
àààààààà//àzweiàseparateàUTF-8àZeichenàdieàdoppeltàkodiertàwurden
ààààààààifà((b2à&à0xC0)à===à0xC0)à{
àààààààààà//àReinterpretiereàdiesesàByteàalsàLatin1àundàkonvertiereàzuàUTF-8
ààààààààààfixedstrà+=àBuffer.from([b],à'latin1').toString('utf8');
àààààààààài++;
ààààààààààcontinue;
àààààààà}
àààààà}
ààààààfixedstrà+=àString.fromCharCode(b);
àààààài++;
àààà}
àààà
ààààifà(fixedstrà!==àutf8str)à{
ààààààfs.writeFileSync(filePath,àfixedstr,à'utf8');
ààààààconsole.log('Fixedà(bin):à'à+àpath.relative('C:\\WMC\\Projekt_25',àfilePath));
ààààààreturnàtrue;
àààà}
àà}àcatchà(e)à{
àààà//àignore
àà}
ààreturnàfalse;
}

functionàwalkDir(dir)à{
ààtryà{
ààààconstàentriesà=àfs.readdirSync(dir,à{àwithFileTypes:àtrueà});
àààà
ààààforà(constàentryàofàentries)à{
ààààààconstàfullPathà=àpath.join(dir,àentry.name);
àààààà
ààààààifà(entry.isDirectory()à&&à!['node_modules',à'.git'].includes(entry.name))à{
ààààààààwalkDir(fullPath);
àààààà}àelseàifà(entry.isFile()à&&à/\.(html|js|css|json|md)$/.test(entry.name))à{
ààààààààifà(fixFile(fullPath))à{
ààààààààààfixed++;
àààààààà}
àààààà}
àààà}
àà}àcatchà(e)à{
àààà//àignore
àà}
}

walkDir('C:\\WMC\\Projekt_25');
console.log('Fixedà(binaryàapproach)à'à+àfixedà+à'àfiles');
