constàfsà=àrequire('fs');
constàpathà=àrequire('path');

letàfixedà=à0;

functionàfixFile(filePath)à{
ààtryà{
ààààletàcontentà=àfs.readFileSync(filePath,à'latin1');
ààààconstàoriginalà=àcontent;
àààà
àààà//àAlleàmöglichenàfehlerhaftenàUTF-8àByte-Sequenzenà(alsàUnicode-Escape)
àààà//àFormat:à\uXXYYà=àUTF-8àBytesàXXàYYàwennàalsàLatin1àgelesen
àààà
àààà//àBindestricheàundàAnführungszeichen
ààààcontentà=àcontent.split('\u00e2\u0080\u0093').join('');àà//àà(en-dash)
ààààcontentà=àcontent.split('\u00e2\u0080\u0094').join('');àà//àà(em-dash)
ààààcontentà=àcontent.split('\u00e2\u0080\u009c').join('"');àà//à"à(leftàquote)
ààààcontentà=àcontent.split('\u00e2\u0080\u009d').join('"');àà//à"à(rightàquote)
ààààcontentà=àcontent.split('\u00e2\u0080\u0099').join("'");àà//à'à(rightàsingle)
ààààcontentà=àcontent.split('\u00e2\u0080\u0098').join("'");àà//à'à(leftàsingle)
ààààcontentà=àcontent.split('\u00e2\u0080\u00a2').join('¢');àà//à¢à(bullet)
ààààcontentà=àcontent.split('\u00e2\u0080\u00a6').join('¦');àà//à¦à(ellipsis)
àààà
àààà//àSonderzeichen
ààààcontentà=àcontent.split('\u00c2\u00ab').join('«');àà//à«
ààààcontentà=àcontent.split('\u00c2\u00bb').join('»');àà//à»
ààààcontentà=àcontent.split('\u00c2\u00b0').join('°');àà//à°
ààààcontentà=àcontent.split('\u00c2\u00a9').join('é');àà//àé
ààààcontentà=àcontent.split('\u00c2\u00ae').join('®');àà//à®
ààààcontentà=àcontent.split('\u00c2\u00bd').join('½');àà//à½
àààà
àààà//àUmlauteàundàAkzente
ààààcontentà=àcontent.split('\u00c3\u00bc').join('ü');àà//àü
ààààcontentà=àcontent.split('\u00c3\u00b6').join('ö');àà//àö
ààààcontentà=àcontent.split('\u00c3\u00a4').join('ä');àà//àä
ààààcontentà=àcontent.split('\u00c3\u009f').join('ß');àà//àß
ààààcontentà=àcontent.split('\u00c3\u00a9').join('é');àà//àé
ààààcontentà=àcontent.split('\u00c3\u00a8').join('è');àà//àè
ààààcontentà=àcontent.split('\u00c3\u00aa').join('ê');àà//àê
ààààcontentà=àcontent.split('\u00c3\u00ab').join('ë');àà//àë
ààààcontentà=àcontent.split('\u00c3\u00a0').join('à');àà//àà
ààààcontentà=àcontent.split('\u00c3\u00a2').join('');àà//à
ààààcontentà=àcontent.split('\u00c3\u00a3').join('ã');àà//àã
ààààcontentà=àcontent.split('\u00c3\u00a7').join('ç');àà//àç
ààààcontentà=àcontent.split('\u00c3\u00a1').join('á');àà//àá
ààààcontentà=àcontent.split('\u00c3\u00ad').join('í');àà//àí
ààààcontentà=àcontent.split('\u00c3\u00b3').join('ó');àà//àó
ààààcontentà=àcontent.split('\u00c3\u00ba').join('ú');àà//àú
ààààcontentà=àcontent.split('\u00c3\u00b9').join('ù');àà//àù
ààààcontentà=àcontent.split('\u00c3\u00b1').join('ñ');àà//àñ
àààà
àààà//àGroßbuchstaben
ààààcontentà=àcontent.split('\u00c3\u0084').join('Ä');àà//àÄ
ààààcontentà=àcontent.split('\u00c3\u0096').join('Ö');àà//àÖ
ààààcontentà=àcontent.split('\u00c3\u009c').join('Ü');àà//àÜ
ààààcontentà=àcontent.split('\u00c3\u009f').join('ß');àà//àß
àààà
àààà//àWeitereàhäufigeàFehler
ààààcontentà=àcontent.split('\u00c3\u00ad').join('í');
ààààcontentà=àcontent.split('\u00c3\u00ad').join('í');
àààà
àààà//àSpezielleàUnicode-Zeichenàdieàfalschàkodiertàwerden
ààààcontentà=àcontent.split('\u00e2\u0099\u00bf').join('¿');àà//à¿àwheelchair
ààààcontentà=àcontent.split('\u00e2\u009a\u0096').join('ï¸ï¸');àà//àï¸ï¸àscale
àààà
àààà//àSpezielleà"—•ä""àSequenzenà(3-ByteàUTF-8àfalschàgelesen)
ààààcontentà=àcontent.split('\u00c3\u00a2\u00e2\u0080').join('');
ààààcontentà=àcontent.split('\u00c3\u00a2\u00e2\u0081').join('');
àààà
ààààifà(contentà!==àoriginal)à{
ààààààfs.writeFileSync(filePath,àcontent,à'utf8');
ààààààconsole.log('Fixed:à'à+àpath.relative('C:\\WMC\\Projekt_25',àfilePath));
ààààààreturnàtrue;
àààà}
àà}àcatchà(e)à{
àààà//àignore
àà}
ààreturnàfalse;
}

functionàwalkDir(dir)à{
ààtryà{
ààààconstàentriesà=àfs.readdirSync(dir,à{àwithFileTypes:àtrueà});
àààà
ààààforà(constàentryàofàentries)à{
ààààààconstàfullPathà=àpath.join(dir,àentry.name);
àààààà
ààààààifà(entry.isDirectory()à&&à!['node_modules',à'.git'].includes(entry.name))à{
ààààààààwalkDir(fullPath);
àààààà}àelseàifà(entry.isFile()à&&à/\.(html|js|css|json|md)$/.test(entry.name))à{
ààààààààifà(fixFile(fullPath))à{
ààààààààààfixed++;
àààààààà}
àààààà}
àààà}
àà}àcatchà(e)à{
àààà//àignore
àà}
}

walkDir('C:\\WMC\\Projekt_25');
console.log('Fixedà'à+àfixedà+à'àfiles');
