constàfsà=àrequire('fs');
constàpathà=àrequire('path');

letàfixedà=à0;

functionàfixFile(filePath)à{
ààtryà{
ààààletàcontentà=àfs.readFileSync(filePath,à'utf8');
ààààconstàoriginalà=àcontent;
àààà
àààà//àBehandleàALLEàbekanntenàfehlerhaftenàSequenzen
àààà//àDieseàsindàdoppelt-kodierteàUTF-8àZeichen
àààà
ààààconstàreplacementsà=à[
àààààà//àBindestricheàundàAkzente
àààààà['°',à'°'],ààààà//àdegree
àààààà['—',à'—'],àààààà//ànormalizeàdashes
àààààà['—',à'—'],àààààà//ànormalizeàem-dashes
àààààà['—•',à'•'],ààààà//àbullet
àààààà['—¦',à'•'],ààààà//àbulletàvariant
àààààà['—ª',à''],àààààà//àremoveàinvalid
àààààà['—¬',à'"'],ààààà//àquote
àààààà['—é',à'é'],ààààà//àcopyright
àààààà['—®',à'®'],ààààà//àregistered
àààààà
àààààà//àHäufigeàFehler-PatternsàinàWörtern
àààààà['Suche…',à'Suche…'],
àààààà['♿',à'♿'],
àààààà['™¿',à'♿'],
àààààà['⚖',à'⚖️'],
àààààà['—¹',à'•'],
àààààà['—¯',à'ü'],
àààààà['',à'—'],
àààààà['—',à'—'],
àààààà['—•—',à'—'],
àààààà
àààààà//àEmoji-Fehler
àààààà['Ÿ',à''],àààààà//àEntferneàfehlerhafteàEmoji-Starts
àààààà['ŸŽ¯',à'🎯'],
àààààà['Ÿçà',à'🧠'],
àààààà
àààààà//àSpezifischeàFehleràausàderàDatei
àààààà['—¹—¯——¸——',à'Richtlinien'],
àààààà['°—¸"•—¡—¯——¸——',à'Vorgaben'],
àààààà
àààààà//àWeitereàhäufigeàFehler
àààààà['ü',à'ü'],
àààààà['ö',à'ö'],
àààààà['ä',à'ä'],
àààààà['',à''],àààààààà//àEntferneàunerwünschteà
àààààà['',à''],àààààààà//àEntferneàunerwünschteà
àààààà['',à''],àààààààà//àEntferneàunerwünschteà
àààààà['¦',à'•'],ààààààà//àDashàzuàPunkt
àààààà['°',à'°'],ààààààà//àGrad-Zeichenànormalisieren
àààà];
àààà
ààààforà(constà[wrong,àcorrect]àofàreplacements)à{
ààààààwhileà(content.indexOf(wrong)à!==à-1)à{
ààààààààcontentà=àcontent.replace(wrong,àcorrect);
àààààà}
àààà}
àààà
ààààifà(contentà!==àoriginal)à{
ààààààfs.writeFileSync(filePath,àcontent,à'utf8');
ààààààconsole.log('Fixed:à'à+àpath.relative('C:\\WMC\\Projekt_25',àfilePath));
ààààààreturnàtrue;
àààà}
àà}àcatchà(e)à{
àààà//àignore
àà}
ààreturnàfalse;
}

functionàwalkDir(dir)à{
ààtryà{
ààààconstàentriesà=àfs.readdirSync(dir,à{àwithFileTypes:àtrueà});
àààà
ààààforà(constàentryàofàentries)à{
ààààààconstàfullPathà=àpath.join(dir,àentry.name);
àààààà
ààààààifà(entry.isDirectory()à&&à!['node_modules',à'.git'].includes(entry.name))à{
ààààààààwalkDir(fullPath);
àààààà}àelseàifà(entry.isFile()à&&à/\.(html|js|css|json|md)$/.test(entry.name))à{
ààààààààifà(fixFile(fullPath))à{
ààààààààààfixed++;
àààààààà}
àààààà}
àààà}
àà}àcatchà(e)à{
àààà//àignore
àà}
}

walkDir('C:\\WMC\\Projekt_25');
console.log('Fixedà'à+àfixedà+à'àfiles');
