constàfsà=àrequire('fs');
constàpathà=àrequire('path');

letàfixedà=à0;

functionàfixFile(filePath)à{
ààtryà{
àààà//àLeseàalsàBinaryàumàdieàrohenàBytesàzuàbekommen
ààààletàbufà=àfs.readFileSync(filePath);
ààààconstàoriginalà=àbuf.toString();
àààà
àààà//àKonvertiereàzuàStringà-àversucheàUTF-8
ààààletàcontentà=àbuf.toString('utf8');
àààà
àààà//àWennàesànochàFehleràhat,àleseàalsàLatin1àundàkonvertiere
ààààifà(content.includes('—')à||àcontent.includes(''))à{
ààààààcontentà=àbuf.toString('latin1');
àààà}
àààà
ààààconstàoriginalContentà=àcontent;
àààà
àààà//àALLEàmöglichenàKombinationenàvonàFehler-Sequenzen
àààà//àDieseàsindàUTF-8àBytes,àdieàalsàLatin1àoderàISO-8859-1àinterpretiertàwurden
àààà
àààà//à3-ByteàUTF-8àalsà2xàLatin1à(—...àSequenzen)
ààààcontentà=àcontent.split('—•"').join('');àà//àEn-dashàdoppeltàfalsch
ààààcontentà=àcontent.split('—•­').join('');àà//àEm-dashàdoppeltàfalsch
ààààcontentà=àcontent.split('—•').join('');ààààà//àBasis-Fehler
ààààcontentà=àcontent.split('').join('');àààààààà//àWeitereàBasis-Fehler
ààààcontentà=àcontent.split('—').join('');ààààààààà//àGenerischesà—ààPräfix
àààà
àààà//àStandard-Fehlerà(wennànurà1xàfalschàkodiert)
ààààcontentà=àcontent.split('—ü').join('ü');
ààààcontentà=àcontent.split('—ö').join('ö');
ààààcontentà=àcontent.split('—ä').join('ä');
ààààcontentà=àcontent.split('——¬"').join('');
ààààcontentà=àcontent.split('——¬"').join('');
ààààcontentà=àcontent.split('«').join('«');
ààààcontentà=àcontent.split('»').join('»');
ààààcontentà=àcontent.split('°').join('°');
àààà
àààà//àSpezielleàHTML-Entities
ààààcontentà=àcontent.split('—').join('');
ààààcontentà=àcontent.split('—').join('');
ààààcontentà=àcontent.split('—').join('');
ààààcontentà=àcontent.split('—').join('');
ààààcontentà=àcontent.split('«').join('«');
ààààcontentà=àcontent.split('»').join('»');
ààààcontentà=àcontent.split('°').join('°');
àààà
àààà//àWheelchairàiconàFehler
ààààcontentà=àcontent.split('¿').join('¿');
ààààcontentà=àcontent.split('—¢¿').join('¿');
àààà
ààààifà(contentà!==àoriginalContent)à{
ààààààfs.writeFileSync(filePath,àcontent,à'utf8');
ààààààconsole.log('Fixed:à'à+àpath.relative('C:\\WMC\\Projekt_25',àfilePath));
ààààààreturnàtrue;
àààà}
àà}àcatchà(e)à{
àààà//àignore
àà}
ààreturnàfalse;
}

functionàwalkDir(dir)à{
ààtryà{
ààààconstàentriesà=àfs.readdirSync(dir,à{àwithFileTypes:àtrueà});
àààà
ààààforà(constàentryàofàentries)à{
ààààààconstàfullPathà=àpath.join(dir,àentry.name);
àààààà
ààààààifà(entry.isDirectory()à&&à!['node_modules',à'.git'].includes(entry.name))à{
ààààààààwalkDir(fullPath);
àààààà}àelseàifà(entry.isFile()à&&à/\.(html|js|css|json|md)$/.test(entry.name))à{
ààààààààifà(fixFile(fullPath))à{
ààààààààààfixed++;
àààààààà}
àààààà}
àààà}
àà}àcatchà(e)à{
àààà//àignore
àà}
}

walkDir('C:\\WMC\\Projekt_25');
console.log('Fixedà'à+àfixedà+à'àfiles');
