constàfsà=àrequire('fs');
constàpathà=àrequire('path');

letàfixedà=à0;

functionàfixFile(filePath)à{
ààtryà{
ààààconstàbufà=àfs.readFileSync(filePath);
ààààletàcontentà=àbuf.toString('utf8');
ààààconstàoriginalà=àcontent;
àààà
àààà//àWennàdieàDateiàUTF-8àdoppelt-kodiertàist,àsiehtàmanàMusteràwie:
àààà//àc383à(UTF-8àfürà"")à=àByteàC3à(UTF-8àPrefixàfürà2-ByteàZeichen)
àààà//àc283à(UTF-8àfürà"")à=àByteàC2à(UTF-8àPrefix)
àààà
àààà//àVersucheàdieàhäufigstenàdoppelkodiertenàPatternsàzuàfindenàundàzuàreparieren
àààà//àPattern:àc383à+àweiteresàByteà=àü/ö/ä
àààà
àààà//àDieseàReplacementsàfixenàdieàdoppelt-kodiertenàUTF-8àSequenzen
ààààcontentà=àcontent.split('\u00c3\u0083\u00c2\u00bc').join('ü');ààààà//à…üà->àü
ààààcontentà=àcontent.split('\u00c3\u0083\u00c2\u00b6').join('ö');ààààà//à…öà->àö
ààààcontentà=àcontent.split('\u00c3\u0083\u00c2\u00a4').join('ä');ààààà//à…äà->àä
àààà
àààà//àAllgemeineràAnsatz:àErsetzeà"C3à83"à(whichàisàUTF8àencodingàofà"")àmità"C3"à(UTF8àforàsingleàbyteàchar)
àààà//àDasàistàkompliziert,àalsoànutzeàString-Patterns
àààà
àààà//àPatternàwieà"..."àsindàZeichen,àdieàmehrfachàfehlerhaftàkodiertàsind
àààà//àVersucheàdieseàdirektàzuàerkennen
ààààconstàhexPatternsà=à[
àààààà{àhex:à'c383c283c382c283c383c282c382c2a2c383c2a2c383c282c382c282c383c282c382c2ac',àtext:à'—'à},
àààà];
àààà
àààà//àSimpler:àVersucheàalleàBytesàc3à81/82/83/84/85/86...à(doppelt-kodiert)àzuàfixen
àààà//àc3à81à=à,àc3à82à=à‚,àusw.
àààà//àDieseàsindàMarkeràfüràDoppelkodierung
àààà
àààà//àExtrahiereàHexàundàversucheàzuàdekodieren
ààààconstàhexStrà=àbuf.toString('hex');
ààààletànewHexà=àhexStr;
àààà
àààà//àBekannteàdoppelt-kodierteàSequenzenà(Hex)
ààààconstàhexReplacementsà=à[
àààààà//àc383c283...àPatternsà(doppeltàkodierteàUmlaute)
àààààà{àfrom:à'c383c283c382bc',àto:à'c3bc'à},àààà//à…üà->àü
àààààà{àfrom:à'c383c283c282b6',àto:à'c3b6'à},àààà//àü
àààààà{àfrom:à'c383c283c282a4',àto:à'c3a4'à},àààà//àä
àààààà//àAndereàdoppelteàKodierungen
àààààà{àfrom:à'c383c283',àto:à'c3'à},àààààààààààà//àGenerischesà...à->àeinzelnesà3-ByteàUTF8
àààà];
àààà
ààààforà(constàrepàofàhexReplacements)à{
àààààànewHexà=ànewHex.split(rep.from).join(rep.to);
àààà}
àààà
ààààifà(newHexà!==àhexStr)à{
ààààààconstànewBufà=àBuffer.from(newHex,à'hex');
ààààààfs.writeFileSync(filePath,ànewBuf);
ààààààconsole.log('Fixed:à'à+àpath.relative('C:\\WMC\\Projekt_25',àfilePath));
ààààààreturnàtrue;
àààà}
àà}àcatchà(e)à{
ààààconsole.error('Error:à'à+àfilePathà+à'à-à'à+àe.message);
àà}
ààreturnàfalse;
}

functionàwalkDir(dir)à{
ààtryà{
ààààconstàentriesà=àfs.readdirSync(dir,à{àwithFileTypes:àtrueà});
àààà
ààààforà(constàentryàofàentries)à{
ààààààconstàfullPathà=àpath.join(dir,àentry.name);
àààààà
ààààààifà(entry.isDirectory()à&&à!['node_modules',à'.git'].includes(entry.name))à{
ààààààààwalkDir(fullPath);
àààààà}àelseàifà(entry.isFile()à&&à/\.(html|js|css|json|md)$/.test(entry.name))à{
ààààààààifà(fixFile(fullPath))à{
ààààààààààfixed++;
àààààààà}
àààààà}
àààà}
àà}àcatchà(e)à{
àààà//àignore
àà}
}

walkDir('C:\\WMC\\Projekt_25');
console.log('Fixedà'à+àfixedà+à'àfiles');
