constàfsà=àrequire('fs');
constàpathà=àrequire('path');

letàfixedà=à0;

functionàfixFile(filePath)à{
ààtryà{
àààà//àLeseàalsàLatin1à(ISO-8859-1)àumàdieàfehlerhaftàkodiertenàUTF-8àBytesàalsàZeichenàzuàbekommen
ààààconstàbufà=àfs.readFileSync(filePath);
ààààconstàasLatin1à=àbuf.toString('latin1');
àààà
àààà//àVersucheàjetztàzurückàinàUTF-8àzuàenkodieren
àààà//àDiesànimmtàdieàLatin1-BytesàundàinterpretiertàsieàalsàkorrekteàUTF-8àBytes
ààààconstàcorrectBytesà=àBuffer.from(asLatin1,à'latin1');
ààààconstàasUTF8à=àcorrectBytes.toString('utf8');
àààà
àààà//àWennàdasàErgebnisàbesseràaussiehtà(wenigeràfehlerhafteàZeichen),àschreibàesàzurück
ààààconstàerrorCharsà=à(asUTF8.match(/[Ÿ«»°é®½ä\ufffd]/g)à||à[]).length;
ààààconstàoriginalErrorsà=à(asLatin1.match(/[Ÿ«»°é®½ä\ufffd]/g)à||à[]).length;
àààà
ààààifà(errorCharsà<àoriginalErrorsà||à(errorCharsà===à0à&&àoriginalErrorsà>à0))à{
ààààààfs.writeFileSync(filePath,àasUTF8,à'utf8');
ààààààconsole.log('Fixed:à'à+àpath.relative('C:\\WMC\\Projekt_25',àfilePath));
ààààààreturnàtrue;
àààà}
àà}àcatchà(e)à{
àààà//àignore
àà}
ààreturnàfalse;
}

functionàwalkDir(dir)à{
ààtryà{
ààààconstàentriesà=àfs.readdirSync(dir,à{àwithFileTypes:àtrueà});
àààà
ààààforà(constàentryàofàentries)à{
ààààààconstàfullPathà=àpath.join(dir,àentry.name);
àààààà
ààààààifà(entry.isDirectory()à&&à!['node_modules',à'.git'].includes(entry.name))à{
ààààààààwalkDir(fullPath);
àààààà}àelseàifà(entry.isFile()à&&à/\.(html|js|css|json|md)$/.test(entry.name))à{
ààààààààifà(fixFile(fullPath))à{
ààààààààààfixed++;
àààààààà}
àààààà}
àààà}
àà}àcatchà(e)à{
àààà//àignore
àà}
}

walkDir('C:\\WMC\\Projekt_25');
console.log('Fixedà'à+àfixedà+à'àfiles');
