constàfsà=àrequire('fs');
constàpathà=àrequire('path');

letàfixedà=à0;

functionàfixFile(filePath)à{
ààtryà{
ààààletàcontentà=àfs.readFileSync(filePath,à'utf8');
ààààconstàoriginalà=àcontent;
àààà
àààà//àUMFASSENDEàListeàalleràbekanntenàfehlerhaftenàMuster
àààà//àDieseàsindàalleàVariationenàvonàdoppelt-kodiertenàUTF-8àZeichen
àààà
àààà//àSonderzeichenàundàUmlaute
ààààconstàpatternsà=à[
àààààà//àWheelchairàIcon
àààààà['♿',à'♿'],
àààààà['♿',à'♿'],
àààààà
àààààà//àEllipsis
àààààà['…',à'…'],
àààààà['…',à'…'],
àààààà
àààààà//àBulletàpoints
àààààà['•',à'•'],
àààààà['•',à'•'],
àààààà
àààààà//àDashes
àààààà['—',à'—'],
àààààà['—',à'—'],
àààààà['—',à'—'],àà//ànochmalàfüràSicherheit
àààààà['°',à'°'],
àààààà['—',à'—'],
àààààà['—',à'—'],
àààààà
àààààà//àQuotes
àààààà['"',à'"'],
àààààà['€\u009d',à'"'],
àààààà
àààààà//àScale/Balanceàemoji
àààààà['⚖',à'⚖'],
àààààà['⚖️',à'⚖️'],
àààààà
àààààà//àGenerischeàFehler
àààààà['',à''],
àààààà['',à''],
àààààà['',à''],
àààààà
àààààà//àSpecificàfieldàfixes
àààààà['Suche…',à'Suche…'],
àààààà['Suche—',à'Suche'],
àààààà
àààààà//àUmlaute
àààààà['ü',à'ü'],
àààààà['ö',à'ö'],
àààààà['ä',à'ä'],
àààààà['é',à'é'],
àààààà['à',à'à'],
àààààà['ç',à'ç'],
àààà];
àààà
ààààforà(constà[wrong,àcorrect]àofàpatterns)à{
àààààà//àErsetzeàmehrfach,àbisàkeineàFehleràmehr
ààààààletàprevContent;
ààààààdoà{
ààààààààprevContentà=àcontent;
ààààààààcontentà=àcontent.split(wrong).join(correct);
àààààà}àwhileà(contentà!==àprevContentà&&àcontent.indexOf(wrong)à!==à-1);
àààà}
àààà
ààààifà(contentà!==àoriginal)à{
ààààààfs.writeFileSync(filePath,àcontent,à'utf8');
ààààààconsole.log('Fixed:à'à+àpath.relative('C:\\WMC\\Projekt_25',àfilePath));
ààààààreturnàtrue;
àààà}
àà}àcatchà(e)à{
àààà//àignore
àà}
ààreturnàfalse;
}

functionàwalkDir(dir)à{
ààtryà{
ààààconstàentriesà=àfs.readdirSync(dir,à{àwithFileTypes:àtrueà});
àààà
ààààforà(constàentryàofàentries)à{
ààààààconstàfullPathà=àpath.join(dir,àentry.name);
àààààà
ààààààifà(entry.isDirectory()à&&à!['node_modules',à'.git'].includes(entry.name))à{
ààààààààwalkDir(fullPath);
àààààà}àelseàifà(entry.isFile()à&&à/\.(html|js|css|json|md)$/.test(entry.name))à{
ààààààààifà(fixFile(fullPath))à{
ààààààààààfixed++;
àààààààà}
àààààà}
àààà}
àà}àcatchà(e)à{
àààà//àignore
àà}
}

walkDir('C:\\WMC\\Projekt_25');
console.log('Comprehensiveàfix:à'à+àfixedà+à'àfilesàrepaired');
