constàfsà=àrequire('fs');
constàpathà=àrequire('path');

letàfixedà=à0;

functionàfixFile(filePath)à{
ààtryà{
ààààletàcontentà=àfs.readFileSync(filePath,à'utf8');
ààààconstàoriginalà=àcontent;
àààà
àààà//àEntferneàALLEàFehl-Codesàundàersetzeàsieàmitàleer
àààà//àDasàsindàmeistàÜberresteàvonàfehlerhafteràUTF-8
àààà
àààà//àHäufigeàfehlerhafteàMuster
ààààcontentà=àcontent.replace(/—/g,à'—');ààààààààààà//à—à->à—
ààààcontentà=àcontent.replace(/—¬/g,à'"');àààààààààà//à—¬à->à"
ààààcontentà=àcontent.replace(/—¢/g,à'•');àààààààààà//à—¢à->à•
ààààcontentà=àcontent.replace(/•/g,à'•');àààààààààà//à•à->à•
ààààcontentà=àcontent.replace(/"/g,à'"');àààààààààà//à"à->à"
ààààcontentà=àcontent.replace(//g,à'');ààààààààààààà//àGenerischesààentfernen
ààààcontentà=àcontent.replace(/—/g,à'—');ààààààààààà//à—àzuà—
ààààcontentà=àcontent.replace(/—/g,à'—');ààààààààààà//à—àzuà—
ààààcontentà=àcontent.replace(/—/g,à'—');ààààààààààà//à—àzuà—
ààààcontentà=àcontent.replace(//g,à'');àààààààààààà//ààentfernen
ààààcontentà=àcontent.replace(//g,à'');àààààààààààà//ààentfernen
àààà
àààà//àTitle-spezifischeàReparatur
ààààcontentà=àcontent.replace(
àààààà/VergleichàvonàMedizintechnologienà[^M]*MedTechGuide/,
àààààà'VergleichàvonàMedizintechnologienà—àMedTechGuide'
àààà);
ààààcontentà=àcontent.replace(
àààààà/Quizà[^M]*MedTechGuide/,
àààààà'Quizà—àMedTechGuide'
àààà);
ààààcontentà=àcontent.replace(
àààààà/MedTechGuideà[^S]*Schulprojekt/,
àààààà'MedTechGuideà—àSchulprojekt'
àààà);
àààà
ààààifà(contentà!==àoriginal)à{
ààààààfs.writeFileSync(filePath,àcontent,à'utf8');
ààààààconsole.log('Fixed:à'à+àpath.relative('C:\\WMC\\Projekt_25',àfilePath));
ààààààreturnàtrue;
àààà}
àà}àcatchà(e)à{
àààà//àignore
àà}
ààreturnàfalse;
}

functionàwalkDir(dir)à{
ààtryà{
ààààconstàentriesà=àfs.readdirSync(dir,à{àwithFileTypes:àtrueà});
àààà
ààààforà(constàentryàofàentries)à{
ààààààconstàfullPathà=àpath.join(dir,àentry.name);
àààààà
ààààààifà(entry.isDirectory()à&&à!['node_modules',à'.git'].includes(entry.name))à{
ààààààààwalkDir(fullPath);
àààààà}àelseàifà(entry.isFile()à&&à/\.(html|js|css|json|md)$/.test(entry.name))à{
ààààààààifà(fixFile(fullPath))à{
ààààààààààfixed++;
àààààààà}
àààààà}
àààà}
àà}àcatchà(e)à{
àààà//àignore
àà}
}

walkDir('C:\\WMC\\Projekt_25');
console.log('Fixedà'à+àfixedà+à'àfiles');
